<style>
    .purchase-page{--purchase-blue:#1769ef;--purchase-ink:#14213d;--purchase-muted:#72809a;--purchase-line:#e2e9f3;--purchase-bg:#f6f9fd;padding:28px 0 48px;background:var(--purchase-bg);min-height:calc(100vh - 65px)}
    .purchase-shell{max-width:1560px;margin:auto;padding:0 24px}
    .purchase-page-header{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:24px}
    .purchase-title-wrap{display:flex;align-items:center;gap:14px}.purchase-title-icon{display:grid;place-items:center;width:52px;height:52px;border:1px solid var(--purchase-line);border-radius:13px;background:#fff;color:var(--purchase-blue);font-size:21px;box-shadow:0 5px 18px rgba(25,67,120,.06)}
    .purchase-page h1{color:var(--purchase-ink);font-weight:800}.purchase-breadcrumb{color:var(--purchase-muted);font-size:.86rem}.purchase-breadcrumb a{color:inherit}
    .purchase-primary-btn{display:inline-flex;align-items:center;justify-content:center;gap:9px;min-height:46px;padding:10px 19px;border:0;border-radius:8px;background:linear-gradient(135deg,#1769ef,#287fff);color:#fff!important;font-weight:700;box-shadow:0 8px 20px rgba(23,105,239,.2)}
    .purchase-panel,.purchase-stat{border:1px solid var(--purchase-line);border-radius:14px;background:#fff;box-shadow:0 6px 22px rgba(28,63,105,.055)}
    .purchase-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin-bottom:22px}.purchase-stat{display:flex;align-items:center;justify-content:space-between;min-height:126px;padding:22px}.purchase-stat-copy small{display:block;color:var(--purchase-muted);font-weight:700}.purchase-stat-copy strong{display:block;margin-top:8px;color:var(--purchase-ink);font:800 1.25rem/1.3 Arial,sans-serif;direction:ltr}.purchase-stat-icon{display:grid;place-items:center;width:58px;height:58px;border-radius:50%;font-size:23px}.purchase-stat:nth-child(1) .purchase-stat-icon{background:#eaf2ff;color:#1769ef}.purchase-stat:nth-child(2) .purchase-stat-icon{background:#e7f8ef;color:#18a866}.purchase-stat:nth-child(3) .purchase-stat-icon{background:#f0eaff;color:#7d42e8}.purchase-stat:nth-child(4) .purchase-stat-icon{background:#fff1e7;color:#e56b15}
    .purchase-filter{padding:22px;margin-bottom:22px}.purchase-section-title{display:flex;align-items:center;gap:10px;margin:0 0 19px;color:var(--purchase-ink);font-size:1.08rem;font-weight:800}.purchase-filter label,.purchase-form-card label{color:#52627b;font-weight:700}.purchase-page .form-control{min-height:45px;border-color:#d8e1ed;border-radius:7px;background:#fff}.purchase-page .form-control:focus{border-color:#7aafff;box-shadow:0 0 0 3px rgba(23,105,239,.1)}.purchase-filter-actions{display:flex;gap:10px;align-items:center}.purchase-filter-actions .btn{min-height:44px;padding:9px 18px;border-radius:7px;font-weight:700}
    .purchase-list-card{overflow:hidden}.purchase-card-head{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:18px 22px;border-bottom:1px solid var(--purchase-line)}.purchase-card-head h2{margin:0;color:var(--purchase-ink);font-size:1.1rem;font-weight:800}.purchase-card-head p{margin:4px 0 0;color:var(--purchase-muted)}
    .purchase-modern-table{margin:0}.purchase-modern-table thead th{border:0;border-bottom:1px solid var(--purchase-line);background:#fbfcfe;color:#52627b;font-weight:800;white-space:nowrap;padding:14px 16px}.purchase-modern-table td{vertical-align:middle;border-color:#edf1f6;padding:15px 16px}.purchase-number{color:var(--purchase-ink);font:800 .9rem/1.35 Arial,sans-serif}.purchase-ref{color:var(--purchase-muted);font-size:.78rem}.purchase-money{direction:ltr;display:inline-block;font:700 .88rem Arial,sans-serif}.purchase-balance{color:#168452}.purchase-status{display:inline-flex;padding:5px 10px;border-radius:999px;font-size:.76rem;font-weight:800}.purchase-status-draft{background:#fff5dd;color:#a46d00}.purchase-status-received{background:#e6f8ed;color:#168452}.purchase-status-cancelled{background:#eef1f5;color:#6b7587}.purchase-open{display:grid;place-items:center;width:37px;height:37px;border:1px solid #d7e1ee;border-radius:8px;color:#415775!important;background:#fff}.purchase-list-card .card-footer{border-top:1px solid var(--purchase-line);background:#fff}
    .purchase-form-card{padding:24px}.purchase-form-card .table{border:1px solid var(--purchase-line);border-radius:10px;overflow:hidden}.purchase-form-card textarea{min-height:105px}.purchase-action-bar{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}
    @media(max-width:1100px){.purchase-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}
    @media(max-width:767.98px){.purchase-shell{padding:0 12px}.purchase-page-header{align-items:stretch;flex-direction:column}.purchase-page-header .purchase-primary-btn{width:100%}.purchase-stats{grid-template-columns:1fr}.purchase-stat{min-height:105px}.purchase-filter-actions{align-items:stretch;flex-direction:column}.purchase-filter-actions .btn{width:100%}.purchase-modern-table,.purchase-modern-table tbody,.purchase-modern-table tr,.purchase-modern-table td{display:block;width:100%}.purchase-modern-table thead{display:none}.purchase-modern-table tr{margin:10px;border:1px solid var(--purchase-line);border-radius:10px;padding:7px;width:calc(100% - 20px)}.purchase-modern-table td{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:10px;border-top:1px solid #edf1f6}.purchase-modern-table td:first-child{border-top:0}.purchase-modern-table td::before{content:attr(data-label);color:var(--purchase-muted);font-weight:800}.purchase-list-action::before{display:none}.purchase-list-action .purchase-open{width:100%}}
</style>
