@extends('main')
@section('content')
<section class="main-content"><div class="container-fluid px-3 px-md-4">
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h3 class="mb-1">{{ $purchase->purchase_number }}</h3><p class="text-muted mb-0">{{ $purchase->supplier->name }} · {{ $purchase->purchase_date->format('d M Y') }}</p></div><a href="{{ route('admin.purchases.index') }}" class="btn btn-light">خریداریوں پر واپس جائیں</a></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="row mb-3">@foreach([['حالت',['draft'=>'زیرِ تیاری','received'=>'وصول شدہ','cancelled'=>'منسوخ'][$purchase->status] ?? $purchase->status],['کل رقم','روپے '.number_format($purchase->total_amount,2)],['ادا شدہ','روپے '.number_format($purchase->paid_amount,2)],['بقایا','روپے '.number_format($purchase->balance_amount,2)]] as [$label,$value])<div class="col-6 col-lg-3 mb-2"><div class="card h-100"><div class="card-body py-3"><small class="text-muted">{{ $label }}</small><div class="h5 mb-0">{{ $value }}</div></div></div></div>@endforeach</div>
    @if($purchase->status==='draft')<div class="card card-body mb-3"><div class="d-flex flex-wrap align-items-center justify-content-between"><span>مال وصول کرنے سے ہر قطار براہ راست کپڑے کے اسٹاک میں شامل ہو گی۔ مسودہ اسٹاک بدلے بغیر منسوخ کیا جا سکتا ہے۔</span><div><form method="POST" action="{{ route('admin.purchases.receive',$purchase) }}" class="d-inline" onsubmit="return confirm('کیا تمام مال وصول کر کے اسٹاک اپ ڈیٹ کرنا ہے؟')">@csrf @method('PATCH')<button class="btn btn-success">مال وصول کریں</button></form> <form method="POST" action="{{ route('admin.purchases.cancel',$purchase) }}" class="d-inline" onsubmit="return confirm('کیا یہ خریداری مسودہ منسوخ کرنا ہے؟')">@csrf @method('PATCH')<button class="btn btn-outline-danger">مسودہ منسوخ کریں</button></form></div></div></div>@endif
    <div class="card mb-3"><div class="table-responsive"><table class="table mb-0"><thead class="thead-light"><tr><th>آئٹم</th><th>آرڈر شدہ</th><th>وصول شدہ</th><th>واپس شدہ</th><th>فی اکائی لاگت</th><th>کل رقم</th>@if($purchase->status==='received')<th>مال واپس کریں</th>@endif</tr></thead><tbody>
        @foreach($purchase->items as $item)<tr><td><strong>{{ $item->cloth->brand->name ?? 'برانڈ' }}</strong><br>{{ $item->cloth->type->name ?? 'قسم' }} / {{ $item->color }}</td><td>{{ number_format($item->quantity,2) }} میٹر</td><td>{{ number_format($item->received_quantity,2) }} میٹر</td><td>{{ number_format($item->returned_quantity,2) }} میٹر</td><td>روپے {{ number_format($item->unit_cost,2) }}</td><td>روپے {{ number_format($item->line_total,2) }}</td>
            @if($purchase->status==='received')<td>@if((float)$item->received_quantity>(float)$item->returned_quantity)<form method="POST" action="{{ route('admin.purchases.return',$purchase) }}">@csrf<input type="hidden" name="purchase_item_id" value="{{ $item->id }}"><input type="hidden" name="return_date" value="{{ now()->toDateString() }}"><div class="input-group input-group-sm"><input type="number" name="quantity" step="0.01" min="0.01" max="{{ (float)$item->received_quantity-(float)$item->returned_quantity }}" class="form-control" placeholder="میٹر" required><div class="input-group-append"><button class="btn btn-outline-danger">واپس کریں</button></div></div></form>@else<span class="text-muted">مکمل واپس شدہ</span>@endif</td>@endif
        </tr>@endforeach
    </tbody></table></div></div>
    @if($purchase->status==='received' && (float)$purchase->balance_amount>0)<div class="card mb-3"><div class="card-header">سپلائر ادائیگی درج کریں</div><div class="card-body"><form method="POST" action="{{ route('admin.purchases.payment',$purchase) }}">@csrf<div class="form-row align-items-end"><div class="form-group col-md-3 mb-md-0"><label>رقم</label><input type="number" name="amount" step="0.01" min="0.01" max="{{ max(0,(float)$purchase->balance_amount) }}" class="form-control" required></div><div class="form-group col-md-3 mb-md-0"><label>تاریخ</label><input type="date" name="payment_date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="form-group col-md-3 mb-md-0"><label>حوالہ</label><input name="reference" class="form-control"></div><div class="col-md-3"><button class="btn btn-success">ادائیگی درج کریں</button></div></div></form></div></div>@endif
    <div class="row"><div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">ادائیگیاں</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>تاریخ</th><th>حوالہ</th><th>رقم</th></tr></thead><tbody>@forelse($purchase->payments as $payment)<tr><td>{{ $payment->payment_date->format('d M Y') }}</td><td>{{ $payment->reference ?: '—' }}</td><td>روپے {{ number_format($payment->amount,2) }}</td></tr>@empty<tr><td colspan="3" class="text-muted text-center">کوئی ادائیگی نہیں</td></tr>@endforelse</tbody></table></div></div></div><div class="col-lg-6 mb-3"><div class="card h-100"><div class="card-header">واپسی</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>نمبر</th><th>تاریخ</th><th>رقم</th></tr></thead><tbody>@forelse($purchase->returns as $return)<tr><td>{{ $return->return_number }}</td><td>{{ $return->return_date->format('d M Y') }}</td><td>روپے {{ number_format($return->total_amount,2) }}</td></tr>@empty<tr><td colspan="3" class="text-muted text-center">کوئی واپسی نہیں</td></tr>@endforelse</tbody></table></div></div></div></div>
</div></section>
@endsection
