@extends('main')
@section('content')
<style>
    .workspace-hero{border-radius:20px;background:linear-gradient(135deg,#0f4c45,#14966f);color:#fff!important;padding:2rem;box-shadow:0 18px 45px rgba(15,76,69,.16)}.workspace-hero h1{color:#fff!important}.workspace-hero p{color:rgba(255,255,255,.78)!important}.metric-card{height:100%;padding:1.2rem;border:1px solid #e8edf3;border-radius:15px;background:#fff;box-shadow:0 8px 25px rgba(31,45,61,.06)}.metric-card strong{display:block;font-size:1.55rem;color:#19324d}.quick-action{display:flex;align-items:center;gap:.8rem;height:100%;padding:1.1rem;border:1px solid #e4eaf1;border-radius:13px;color:#29445f;background:#fff;font-weight:700}.quick-action:hover{text-decoration:none;border-color:#64bc9e;background:#f3fbf8}.quick-action i{font-size:1.2rem}
</style>
<section class="main-content"><div class="container-fluid px-3 px-md-4 py-4">
    <div class="workspace-hero mb-4 d-flex flex-wrap align-items-center justify-content-between"><div><span class="badge badge-light text-success mb-2">دکان اور فروخت ورک اسپیس</span><h1 class="h2 mb-2">دکان ڈیش بورڈ</h1><p class="mb-0">فروخت، اسٹاک، سپلائر اور خریداری کا روزمرہ انتظام۔</p></div>@if(Auth::user()->enabledModules() === ['tailoring','clothing'])<a href="{{ route('admin.home') }}" class="btn btn-light mt-3 mt-md-0"><i class="fas fa-random ml-1"></i> ورک اسپیس تبدیل کریں</a>@endif</div>
    <div class="row mb-3">
        @if($canInventory)@foreach([['اسٹاک میں میٹر',number_format($clothing['meters'],2),'primary'],['اسٹاک کی مالیت','روپے '.number_format($clothing['inventory_value'],0),'info'],['کم اسٹاک اشیاء',$clothing['low_stock'],'warning']] as [$label,$value,$color])<div class="col-6 col-xl mb-3"><div class="metric-card"><small class="text-muted">{{ $label }}</small><strong class="text-{{ $color }}">{{ $value }}</strong></div></div>@endforeach @endif
        @if($canPurchases)<div class="col-6 col-xl mb-3"><div class="metric-card"><small class="text-muted">زیرِ تیاری خریداریاں</small><strong class="text-secondary">{{ $clothing['draft_purchases'] }}</strong></div></div>@endif
        @if($canSales)<div class="col-6 col-xl mb-3"><div class="metric-card"><small class="text-muted">اس ماہ کی فروخت</small><strong class="text-success">روپے {{ number_format($clothing['month_sales'],0) }}</strong></div></div>@endif
    </div>
    <div class="row">@if($canSales)<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.sellCloth') }}"><i class="fas fa-cash-register text-success"></i> نئی فروخت</a></div>@endif @if($canInventory)<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.stock.index') }}"><i class="fas fa-layer-group text-success"></i> اسٹاک</a></div>@endif @if($canPurchases)<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.purchases.index') }}"><i class="fas fa-truck-loading text-success"></i> خریداریاں</a></div>@endif @if(Auth::user()->hasBusinessPermission('clothing.suppliers'))<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.suppliers.index') }}"><i class="fas fa-building text-success"></i> سپلائرز</a></div>@endif</div>
</div></section>
@endsection
