@extends('main')
@section('content')
<style>
    .workspace-hero{border-radius:20px;background:linear-gradient(135deg,#102a43,#1769a8);color:#fff!important;padding:2rem;box-shadow:0 18px 45px rgba(16,42,67,.16)}.workspace-hero h1{color:#fff!important}.workspace-hero p{color:rgba(255,255,255,.76)!important}.metric-card{height:100%;padding:1.2rem;border:1px solid #e8edf3;border-radius:15px;background:#fff;box-shadow:0 8px 25px rgba(31,45,61,.06)}.metric-card strong{display:block;font-size:1.65rem;color:#19324d}.quick-action{display:flex;align-items:center;gap:.8rem;height:100%;padding:1.1rem;border:1px solid #e4eaf1;border-radius:13px;color:#29445f;background:#fff;font-weight:700}.quick-action:hover{text-decoration:none;border-color:#72a8e8;background:#f5f9ff}.quick-action i{font-size:1.2rem}
</style>
<section class="main-content"><div class="container-fluid px-3 px-md-4 py-4">
    <div class="workspace-hero mb-4 d-flex flex-wrap align-items-center justify-content-between"><div><span class="badge badge-light text-primary mb-2">ٹیلرنگ ورک اسپیس</span><h1 class="h2 mb-2">ٹیلرنگ ڈیش بورڈ</h1><p class="mb-0">آرڈر سے حوالگی تک ورکشاپ کی تمام پیش رفت ایک جگہ۔</p></div>@if(Auth::user()->enabledModules() === ['tailoring','clothing'])<a href="{{ route('admin.home') }}" class="btn btn-light mt-3 mt-md-0"><i class="fas fa-random ml-1"></i> ورک اسپیس تبدیل کریں</a>@endif</div>
    <div class="row mb-3">@if($canWorkshop)@foreach([['جاری کام',$tailoring['active'],'primary'],['آج واجب',$tailoring['due_today'],'warning'],['تیار',$tailoring['ready'],'success']] as [$label,$value,$color])<div class="col-6 col-xl-3 mb-3"><div class="metric-card"><small class="text-muted">{{ $label }}</small><strong class="text-{{ $color }}">{{ number_format($value) }}</strong></div></div>@endforeach @endif @if($canOrders)<div class="col-6 col-xl-3 mb-3"><div class="metric-card"><small class="text-muted">اس ماہ کے سوٹ</small><strong class="text-info">{{ number_format($tailoring['month_suits']) }}</strong></div></div>@endif</div>
    <div class="row">@if(Auth::user()->hasBusinessPermission('tailoring.customers'))<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.Customers.create') }}"><i class="fas fa-user-plus text-primary"></i> نیا گاہک</a></div>@endif @if(Auth::user()->hasBusinessPermission('tailoring.workshop'))<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.tailor-jobs.index') }}"><i class="fas fa-tasks text-primary"></i> کام کی فہرست</a></div>@endif @if(Auth::user()->hasBusinessPermission('tailoring.orders'))<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.order.total') }}"><i class="fas fa-clipboard-list text-primary"></i> ٹیلرنگ آرڈرز</a></div>@endif @if(Auth::user()->hasBusinessPermission('tailoring.customers'))<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.Customers.index') }}"><i class="fas fa-user-friends text-primary"></i> گاہک اور پیمائش</a></div>@endif @if(Auth::user()->hasBusinessPermission('tailoring.tailors'))<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.Tailor.index') }}"><i class="fas fa-user-cog text-primary"></i> درزی</a></div>@endif @if(Auth::user()->hasBusinessPermission('tailoring.configuration'))<div class="col-md-3 mb-3"><a class="quick-action" href="{{ route('admin.OptionType.index') }}"><i class="fas fa-ruler-combined text-primary"></i> پیمائش کے اختیارات</a></div>@endif</div>
</div></section>
@endsection
