@extends('storefront.public.layout')
@section('title', $service->localizedName().' — '.$storefront->localizedName())
@section('meta_description', $service->localizedDescription() ?: __('storefront.tailoring.default_description'))
@section('canonical_url', route('storefront.tailoring.show',[$storefront,$service]))
@push('structured_data')
<script type="application/ld+json">{!! \App\Support\StorefrontSeo::json(\App\Support\StorefrontSeo::graph(
    \App\Support\StorefrontSeo::service($storefront,$service)
)) !!}</script>
@endpush
@push('styles')
@include('storefront.public.partials.shop-navigation-styles')
.order-config{display:grid;grid-template-columns:.8fr 1.2fr;gap:24px}.method-card{display:block;border:1px solid var(--line);border-radius:12px;padding:11px;margin:8px 0;background:#fafcfb}.method-card input{margin-inline-end:7px}.measurement-panel{display:none;margin-top:14px;padding:15px;border:1px solid var(--line);border-radius:12px;background:#f7faf8}.measurement-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.measurement-panel.is-visible{display:block}.profile-details{display:none;margin-top:12px;padding:12px;border-radius:10px;background:#fff}.profile-details.is-visible{display:block}.profile-values{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:9px}.profile-value{display:flex;justify-content:space-between;gap:12px;padding:8px;border-bottom:1px solid var(--line)}@media(max-width:800px){.order-config{grid-template-columns:1fr}.measurement-grid,.profile-values{grid-template-columns:1fr}}
@endpush
@section('body')
@include('storefront.public.partials.shop-navigation')
@php
    $publicMeasurementMethods = collect($service->availableMeasurementMethods())
        ->reject(fn ($method) => $method === \App\Models\StorefrontTailoringService::MEASUREMENT_STANDARD_SIZE && $standardProfiles->isEmpty())
        ->values();
@endphp
<main class="section"><div class="shell order-config">
<article class="card panel"><h1>{{ $service->localizedName() }}</h1><div class="meta">@if($service->price_from!==null)<span class="pill">{!! \App\Support\PakistanCurrency::html($service->price_from) !!} · {{ $service->localizedPriceUnit() }}</span>@endif @if($service->estimated_days)<span class="pill">{{ __('storefront.tailoring.estimated_days',['days'=>$service->estimated_days]) }}</span>@endif</div><p>{{ $service->localizedDescription() ?: __('storefront.tailoring.default_description') }}</p><div class="notice">{{ __('storefront.tailoring.unified_service_notice') }}</div></article>
<section class="card">
@if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
@if(!$service->is_available)<div class="notice">{{ __('storefront.tailoring.temporarily_unavailable') }}</div>
@elseif($service->price_from===null || !$service->accepts_inquiries)<div class="notice">{{ __('storefront.tailoring.order_unavailable') }}</div>@else
<h2>{{ __('storefront.tailoring.configure_title') }}</h2>
<form method="POST" action="{{ route('storefront.tailoring.cart.store',[$storefront,$service]) }}">@csrf
<input type="hidden" name="clothing_cart_item_id" value="{{ request('cloth_item') }}">
<div class="form-group"><label>{{ __('storefront.tailoring.measurement_method') }}</label>@foreach($publicMeasurementMethods as $method)<label class="method-card"><input type="radio" name="measurement_method" value="{{ $method }}" @checked(old('measurement_method')===$method) required> {{ __('storefront.tailoring.measurement_methods.'.$method) }}</label>@endforeach</div>
<div id="standard-size-panel" class="measurement-panel"><label for="standard_measurement_profile_id">{{ __('storefront.tailoring.standard_size') }}</label><select id="standard_measurement_profile_id" name="standard_measurement_profile_id" class="control"><option value="">{{ __('storefront.common.select') }}</option>@foreach($standardProfiles as $profile)<option value="{{ $profile->id }}" @selected((string)old('standard_measurement_profile_id')===(string)$profile->id)>{{ $profile->name }}</option>@endforeach</select><small>{{ __('storefront.tailoring.standard_profile_help') }}</small><div id="profile-details-empty" class="profile-details is-visible"><small>{{ __('storefront.tailoring.select_profile_for_details') }}</small></div>@foreach($standardProfiles as $profile)<article class="profile-details" data-profile-details="{{ $profile->id }}"><strong>{{ __('storefront.tailoring.saved_measurement_details') }} — {{ $profile->name }}</strong><div class="profile-values">@foreach($profile->measurement_values ?? [] as $measurement)<div class="profile-value"><span>{{ $measurement['label'] ?? $measurement['source_key'] ?? '' }}</span><strong>{{ $measurement['value'] ?? '' }} @if(!empty($measurement['unit'])){{ $measurement['unit'] }}@endif</strong></div>@endforeach</div></article>@endforeach</div>
<div id="custom-measurements-panel" class="measurement-panel"><h3>{{ $service->measurementTemplate?->name ?: __('storefront.tailoring.custom_measurements') }}</h3>@if(!$service->measurementTemplate)<div class="errors">{{ __('storefront.messages.measurement_template_required') }}</div>@else<div class="measurement-grid">@foreach($systemFields as $key=>$meta)<div class="form-group"><label for="measure_system_{{ $key }}">{{ $meta['label'] }} @if($meta['unit'])({{ $meta['unit'] }})@endif</label><input id="measure_system_{{ $key }}" name="measurements[system][{{ $key }}]" class="control" value="{{ old('measurements.system.'.$key) }}"></div>@endforeach @foreach($customFields as $field)<div class="form-group"><label for="measure_custom_{{ $field->id }}">{{ $field->label }} @if($field->unit!=='none')({{ $field->unit }})@endif</label>@if($field->field_type==='select')<select id="measure_custom_{{ $field->id }}" name="measurements[custom][{{ $field->id }}]" class="control"><option value="">{{ __('storefront.common.select') }}</option>@foreach($field->options ?? [] as $option)<option value="{{ $option }}" @selected(old('measurements.custom.'.$field->id)===$option)>{{ $option }}</option>@endforeach</select>@else<input id="measure_custom_{{ $field->id }}" name="measurements[custom][{{ $field->id }}]" type="{{ $field->field_type==='number' ? 'number' : 'text' }}" @if($field->field_type==='number') step="0.01" min="0" @endif class="control" value="{{ old('measurements.custom.'.$field->id) }}">@endif</div>@endforeach</div>@endif</div>
<div class="form-group"><label for="tailoring_quantity">{{ __('storefront.tailoring.suit_quantity') }}</label><input id="tailoring_quantity" type="number" name="quantity" min="1" max="20" class="control" value="{{ old('quantity',1) }}" required></div>
<div class="form-group"><label for="preferred_date">{{ __('storefront.tailoring.preferred_date') }}</label><input id="preferred_date" type="date" min="{{ now()->toDateString() }}" name="preferred_date" class="control" value="{{ old('preferred_date') }}"></div>
<div class="form-group"><label for="tailoring_notes">{{ __('storefront.tailoring.details_question') }}</label><textarea id="tailoring_notes" name="notes" maxlength="2000" rows="3" class="control">{{ old('notes') }}</textarea></div>
<button class="btn" style="width:100%">{{ __('storefront.tailoring.add_to_order') }}</button>
</form>@endif
</section></div></main>
@include('storefront.public.partials.shop-footer')
@endsection
@push('scripts')<script>(()=>{const standard=document.getElementById('standard-size-panel'),custom=document.getElementById('custom-measurements-panel'),profileSelect=document.getElementById('standard_measurement_profile_id'),empty=document.getElementById('profile-details-empty');const refreshProfile=()=>{const selected=profileSelect?.value||'';document.querySelectorAll('[data-profile-details]').forEach(panel=>panel.classList.toggle('is-visible',panel.dataset.profileDetails===selected));empty?.classList.toggle('is-visible',selected==='')};const refresh=()=>{const method=document.querySelector('input[name="measurement_method"]:checked')?.value;standard?.classList.toggle('is-visible',method==='standard_size');custom?.classList.toggle('is-visible',method==='custom_measurements');if(profileSelect)profileSelect.required=method==='standard_size';refreshProfile()};document.querySelectorAll('input[name="measurement_method"]').forEach(input=>input.addEventListener('change',refresh));profileSelect?.addEventListener('change',refreshProfile);refresh()})()</script>@endpush
