@extends('main')
@section('content')
<section class="main-content merchandising-admin"><style>
.merchandising-admin{background:#f3f7f8;min-height:calc(100vh - 70px)}.merch-hero{background:linear-gradient(135deg,#163c31,#1b7d5b);color:#fff;border-radius:20px;padding:1.5rem 1.7rem}.merch-card{border:0;border-radius:18px;box-shadow:0 9px 28px rgba(31,45,61,.08)}.choice-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.55rem}.choice-grid label{background:#fff;border:1px solid #dfe9e4;border-radius:8px;padding:.55rem}.item-chip{display:inline-flex;align-items:center;background:#e5f3ed;border-radius:999px;padding:.25rem .65rem;font-size:.8rem}.menu-row{border:1px solid #e2ebe7;border-radius:12px;padding:1rem;margin-bottom:.8rem;background:#fff}.submenu{margin-right:2rem;border-right:3px solid #d8e8e0;padding-right:1rem}@media(max-width:767px){.choice-grid{grid-template-columns:1fr}.merch-hero{border-radius:14px}.submenu{margin-right:.5rem}}
</style><div class="container-fluid px-3 px-md-4 py-4" dir="rtl">
<div class="merch-hero mb-4 d-flex flex-wrap justify-content-between align-items-center"><div><div class="small">آن لائن دکان</div><h1 class="h3 text-white mb-1">ہیرو، کلیکشن اور مینو</h1><p class="mb-0 text-white-50">متعدد تصویری یا ویڈیو سلائیڈز، مصنوعات کی کلیکشنز اور دو لسانی مینو ایک جگہ ترتیب دیں۔</p></div><div class="mt-3 mt-md-0"><a href="{{ route('admin.storefront.clothing.index') }}" class="btn btn-light ml-2">پروڈکٹ فہرست</a><a href="{{ route('admin.storefront.edit') }}" class="btn btn-outline-light">برانڈنگ</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card merch-card mb-4"><div class="card-header bg-white"><h2 class="h5 mb-1">نئی ہیرو سلائیڈ</h2><p class="small text-muted mb-0">ہر سلائیڈ کے لیے الگ تصویر یا ویڈیو، اردو/English متن اور دو فوری بٹن رکھیں۔ موجودہ واحد ہیرو تب تک fallback رہے گا جب تک کوئی فعال سلائیڈ نہ ہو۔</p></div><form method="POST" enctype="multipart/form-data" action="{{ route('admin.storefront.hero-slides.store') }}" class="card-body">@csrf @include('storefront.admin.partials.hero-slide-fields',['heroSlide'=>null])</form></div>
<div class="mb-4"><h2 class="h4">ہیرو سلائیڈز</h2>@forelse($heroSlides as $heroSlide)<details class="card merch-card mb-3"><summary class="card-header bg-white d-flex justify-content-between"><strong>{{ $heroSlide->title_ur ?: $heroSlide->title_en }}</strong><span><span class="item-chip">{{ $heroSlide->media_type }}</span> · {{ $heroSlide->is_active?'فعال':'غیر فعال' }} · ترتیب {{ $heroSlide->sort_order }}</span></summary><form method="POST" enctype="multipart/form-data" action="{{ route('admin.storefront.hero-slides.update',$heroSlide) }}" class="card-body">@csrf @method('PUT') @include('storefront.admin.partials.hero-slide-fields',['heroSlide'=>$heroSlide])</form><form method="POST" action="{{ route('admin.storefront.hero-slides.destroy',$heroSlide) }}" class="px-3 pb-3" data-confirm="کیا آپ یہ سلائیڈ حذف کرنا چاہتے ہیں؟" data-confirm-variant="danger">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">حذف کریں</button></form></details>@empty<div class="alert alert-light">ابھی سلائیڈ نہیں بنائی گئی؛ موجودہ برانڈنگ ہیرو استعمال ہو رہا ہے۔</div>@endforelse</div>
<div class="card merch-card mb-4"><div class="card-header bg-white"><h2 class="h5 mb-0">نئی کلیکشن بنائیں</h2></div><form method="POST" action="{{ route('admin.storefront.collections.store') }}" class="card-body collection-form">@csrf @include('storefront.admin.partials.collection-fields',['collection'=>null])</form></div>
<div class="mb-4"><h2 class="h4">موجودہ کلیکشنز</h2>@forelse($collections as $collection)<details class="card merch-card mb-3"><summary class="card-header bg-white d-flex justify-content-between"><strong>{{ $collection->name_ur ?: $collection->name_en }}</strong><span><span class="item-chip">{{ $collection->source_type }}</span> · {{ $collection->is_published?'شائع شدہ':'مسودہ' }} · {{ $collection->menu_items_count }} مینو</span></summary><form method="POST" action="{{ route('admin.storefront.collections.update',$collection) }}" class="card-body collection-form">@csrf @method('PUT') @include('storefront.admin.partials.collection-fields',['collection'=>$collection])</form><form method="POST" action="{{ route('admin.storefront.collections.destroy',$collection) }}" class="px-3 pb-3" data-confirm="کیا آپ یہ کلیکشن حذف کرنا چاہتے ہیں؟" data-confirm-variant="danger">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">حذف کریں</button></form></details>@empty<div class="alert alert-light">ابھی کوئی کلیکشن نہیں۔</div>@endforelse</div>
<div class="card merch-card mb-4"><div class="card-header bg-white"><h2 class="h5 mb-1">نیا مینو آئٹم</h2><p class="small text-muted mb-0">مینو میں کلیکشن، مکمل کیٹلاگ، ٹیلرنگ، رابطہ یا بیرونی لنک شامل کریں۔ والد منتخب کر کے ایک سطح کا ذیلی مینو بنائیں۔</p></div><form method="POST" action="{{ route('admin.storefront.menu-items.store') }}" class="card-body">@csrf @include('storefront.admin.partials.menu-fields',['menuItem'=>null])</form></div>
<div><h2 class="h4">مینو ترتیب</h2>@forelse($menuItems as $menuItem)<div class="menu-row"><form method="POST" action="{{ route('admin.storefront.menu-items.update',$menuItem) }}">@csrf @method('PUT') @include('storefront.admin.partials.menu-fields',['menuItem'=>$menuItem])</form><form method="POST" action="{{ route('admin.storefront.menu-items.destroy',$menuItem) }}" data-confirm="یہ مینو آئٹم حذف کریں؟" data-confirm-variant="danger">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">حذف</button></form>@foreach($menuItem->children as $child)<div class="submenu mt-3"><form method="POST" action="{{ route('admin.storefront.menu-items.update',$child) }}">@csrf @method('PUT') @include('storefront.admin.partials.menu-fields',['menuItem'=>$child])</form><form method="POST" action="{{ route('admin.storefront.menu-items.destroy',$child) }}" data-confirm="یہ ذیلی مینو آئٹم حذف کریں؟" data-confirm-variant="danger">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">حذف</button></form></div>@endforeach</div>@empty<div class="alert alert-light">ابھی نیا مینو ترتیب نہیں دیا گیا؛ موجودہ ڈیفالٹ مینو دکھتا رہے گا۔</div>@endforelse</div>
</div></section>
@endsection
@push('scripts')<script>(()=>{document.querySelectorAll('.collection-form').forEach(form=>{const select=form.querySelector('.collection-source');const refresh=()=>form.querySelectorAll('[data-source]').forEach(panel=>{const value=select.value;panel.hidden=panel.dataset.source!==( ['manual','category','brand','tag'].includes(value)?value:'automatic')});select.addEventListener('change',refresh);refresh()})})()</script>@endpush
