@extends('main')
@section('content')
<section class="main-content"><div class="container-fluid px-3 px-md-4">
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-3"><div><h3 class="mb-1">اسٹاک کھاتہ</h3><p class="text-muted mb-0">خریداری، فروخت، آن لائن آرڈرز اور تبدیلیوں کی مکمل اسٹاک نقل و حرکت۔</p></div><div><a href="{{ route('admin.inventory-valuation.index') }}" class="btn btn-primary">اسٹاک کی مالیت</a> <a href="{{ route('admin.purchases.index') }}" class="btn btn-outline-primary">خریداریاں</a></div></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="card card-body mb-3"><h5>اسٹاک میں دستی تبدیلی</h5><form method="POST" action="{{ route('admin.inventory-ledger.adjust') }}">@csrf<div class="form-row align-items-end"><div class="form-group col-lg-4"><label>اسٹاک آئٹم</label><select name="cloth_color_id" class="form-control" required><option value="">آئٹم منتخب کریں</option>@foreach($colors as $color)<option value="{{ $color->id }}">{{ $color->cloth->brand->name ?? 'برانڈ' }} / {{ $color->cloth->type->name ?? 'قسم' }} / {{ $color->color }} ({{ number_format($color->length,2) }} میٹر)</option>@endforeach</select></div><div class="form-group col-lg-2"><label>سمت</label><select name="direction" class="form-control" required><option value="increase">اضافہ</option><option value="decrease">کمی</option></select></div><div class="form-group col-lg-2"><label>مقدار (میٹر)</label><input type="number" name="quantity" step="0.01" min="0.01" class="form-control" required></div><div class="form-group col-lg-2"><label>فی اکائی لاگت</label><input type="number" name="unit_cost" step="0.01" min="0" class="form-control"></div><div class="form-group col-lg-2"><label>وجہ</label><input name="note" maxlength="1000" class="form-control" required></div></div><button class="btn btn-warning">تبدیلی درج کریں</button></form></div>
    <form class="card card-body mb-3" method="GET">
        <div class="form-row align-items-end">
            <div class="form-group col-lg-4"><label>اسٹاک آئٹم</label><select name="cloth_color_id" class="form-control"><option value="">تمام اسٹاک اشیاء</option>@foreach($colors as $color)<option value="{{ $color->id }}" @selected((int)($validated['cloth_color_id']??0)===$color->id)>{{ $color->cloth->brand->name ?? 'برانڈ' }} / {{ $color->cloth->type->name ?? 'قسم' }} / {{ $color->color }} — موجودہ {{ number_format($color->length,2) }} میٹر</option>@endforeach</select></div>
            <div class="form-group col-lg-3"><label>نقل و حرکت</label><select name="movement_type" class="form-control"><option value="">تمام نقل و حرکت</option>@foreach(['purchase_receipt','purchase_return','counter_sale','online_order','online_cancellation','online_reorder','cart_reservation','cart_release','storefront_order','storefront_cancellation','storefront_return','storefront_exchange_issue','manual_adjustment_in','manual_adjustment_out'] as $type)<option value="{{ $type }}" @selected(($validated['movement_type']??'')===$type)>{{ ['purchase_receipt'=>'خریداری وصولی','purchase_return'=>'خریداری واپسی','counter_sale'=>'کاؤنٹر فروخت','online_order'=>'آن لائن آرڈر','online_cancellation'=>'آن لائن منسوخی','online_reorder'=>'آن لائن دوبارہ آرڈر','cart_reservation'=>'کارٹ میں محفوظ','cart_release'=>'کارٹ سے واپسی','storefront_order'=>'عوامی دکان آرڈر','storefront_cancellation'=>'عوامی دکان منسوخی','storefront_return'=>'عوامی دکان واپسی','storefront_exchange_issue'=>'عوامی دکان متبادل اجرا','manual_adjustment_in'=>'دستی اضافہ','manual_adjustment_out'=>'دستی کمی'][$type] }}</option>@endforeach</select></div>
            <div class="form-group col-lg-2"><label>شروع تاریخ</label><input type="date" name="from_date" value="{{ $validated['from_date'] ?? '' }}" class="form-control"></div>
            <div class="form-group col-lg-2"><label>آخری تاریخ</label><input type="date" name="to_date" value="{{ $validated['to_date'] ?? '' }}" class="form-control"></div>
            <div class="form-group col-lg-1"><label>قطاریں</label><select name="per_page" class="form-control">@foreach([15,25,50,100] as $size)<option value="{{ $size }}" @selected((int)($validated['per_page']??25)===$size)>{{ $size }}</option>@endforeach</select></div>
        </div><div><button class="btn btn-primary">فلٹر کریں</button> <a href="{{ route('admin.inventory-ledger.index') }}" class="btn btn-light">صاف کریں</a></div>
    </form>
    <div class="card"><div class="card-header py-2 text-muted small">کل {{ $movements->total() }} اندراجات میں سے {{ $movements->firstItem() ?? 0 }}–{{ $movements->lastItem() ?? 0 }} دکھائے جا رہے ہیں</div><div class="table-responsive"><table class="table table-hover mb-0"><thead class="thead-light"><tr><th>تاریخ</th><th>اسٹاک آئٹم</th><th>نقل و حرکت</th><th>مقدار</th><th>بعد کا بقایا</th><th>فی اکائی لاگت</th><th>حوالہ</th></tr></thead><tbody>
        @forelse($movements as $movement)<tr><td>{{ $movement->occurred_at->format('d M Y H:i') }}</td><td>{{ $movement->cloth->brand->name ?? 'برانڈ' }} / {{ $movement->cloth->type->name ?? 'قسم' }} / {{ $movement->clothColor->color ?? '' }}</td><td>{{ ['purchase_receipt'=>'خریداری وصولی','purchase_return'=>'خریداری واپسی','counter_sale'=>'کاؤنٹر فروخت','online_order'=>'آن لائن آرڈر','online_cancellation'=>'آن لائن منسوخی','online_reorder'=>'آن لائن دوبارہ آرڈر','cart_reservation'=>'کارٹ میں محفوظ','cart_release'=>'کارٹ سے واپسی','storefront_order'=>'عوامی دکان آرڈر','storefront_cancellation'=>'عوامی دکان منسوخی','storefront_return'=>'عوامی دکان واپسی','storefront_exchange_issue'=>'عوامی دکان متبادل اجرا','manual_adjustment_in'=>'دستی اضافہ','manual_adjustment_out'=>'دستی کمی'][$movement->movement_type] ?? $movement->movement_type }}</td><td class="{{ (float)$movement->quantity>=0?'text-success':'text-danger' }}"><strong>{{ (float)$movement->quantity>=0?'+':'' }}{{ number_format($movement->quantity,2) }} میٹر</strong></td><td>{{ $movement->balance_after===null?'—':number_format($movement->balance_after,2).' میٹر' }}</td><td>{{ $movement->unit_cost!==null?'روپے '.number_format($movement->unit_cost,2):'—' }}</td><td>{{ $movement->note }}</td></tr>
        @empty<tr><td colspan="7" class="text-center text-muted py-5">منتخب فلٹر کے مطابق اسٹاک کی کوئی نقل و حرکت موجود نہیں۔</td></tr>@endforelse
    </tbody></table></div>@if($movements->hasPages())<div class="card-footer">{{ $movements->links() }}</div>@endif</div>
</div></section>
@endsection
