@extends('main')
@section('content')
<section class="main-content"><div class="container-fluid px-3 px-md-4">
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-3"><div><h3 class="mb-1">اسٹاک کی مالیت</h3><p class="text-muted mb-0">موجودہ اسٹاک کی اوسط لاگت کے مطابق مالیت۔</p></div><a href="{{ route('admin.inventory-ledger.index') }}" class="btn btn-outline-primary">اسٹاک کھاتہ</a></div>
    <form method="GET" class="card card-body mb-3"><div class="form-row align-items-end"><div class="form-group col-md-8 mb-md-0"><label>اسٹاک تلاش کریں</label><input name="q" maxlength="100" class="form-control" value="{{ $validated['q'] ?? '' }}" placeholder="برانڈ، کپڑے کی قسم یا رنگ"></div><div class="form-group col-md-2 mb-md-0"><label>قطاریں</label><select name="per_page" class="form-control">@foreach([15,25,50,100] as $size)<option value="{{ $size }}" @selected((int)($validated['per_page']??25)===$size)>{{ $size }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary">فلٹر کریں</button> <a class="btn btn-light" href="{{ route('admin.inventory-valuation.index') }}">صاف کریں</a></div></div></form>
    <div class="row mb-3">@foreach([['موجودہ میٹر',$totals['meters'].' میٹر','primary'],['اسٹاک کی لاگت','روپے '.number_format($totals['cost'],2),'info'],['فروختی مالیت','روپے '.number_format($totals['retail'],2),'success'],['ممکنہ منافع','روپے '.number_format($totals['margin'],2),$totals['margin']>=0?'success':'danger']] as [$label,$value,$color])<div class="col-6 col-lg-3 mb-2"><div class="card h-100"><div class="card-body"><small class="text-muted">{{ $label }}</small><div class="h5 text-{{ $color }} mb-0">{{ $value }}</div></div></div></div>@endforeach</div>
    <div class="card"><div class="card-header py-2 text-muted small">کل {{ $colors->total() }} اسٹاک اشیاء میں سے {{ $colors->firstItem() ?? 0 }}–{{ $colors->lastItem() ?? 0 }} دکھائی جا رہی ہیں</div><div class="table-responsive"><table class="table table-hover mb-0"><thead class="thead-light"><tr><th>برانڈ</th><th>قسم</th><th>رنگ</th><th>موجودہ مقدار</th><th>اوسط لاگت</th><th>کل لاگت</th><th>فروختی قیمت</th><th>فروختی مالیت</th><th>منافع</th></tr></thead><tbody>
        @forelse($colors as $color)@php($costValue=(float)$color->length*(float)$color->average_unit_cost) @php($retailValue=(float)$color->length*(float)($color->cloth->sale_price??0))<tr><td>{{ $color->cloth->brand->name ?? '—' }}</td><td>{{ $color->cloth->type->name ?? '—' }}</td><td>{{ $color->color }}</td><td>{{ number_format($color->length,2) }}m</td><td>Rs {{ number_format($color->average_unit_cost,2) }}</td><td>Rs {{ number_format($costValue,2) }}</td><td>Rs {{ number_format($color->cloth->sale_price??0,2) }}</td><td>Rs {{ number_format($retailValue,2) }}</td><td>Rs {{ number_format($retailValue-$costValue,2) }}</td></tr>
        @empty<tr><td colspan="9" class="text-center text-muted py-5">منتخب فلٹر کے مطابق کپڑے کا کوئی اسٹاک موجود نہیں۔</td></tr>@endforelse
    </tbody></table></div>@if($colors->hasPages())<div class="card-footer">{{ $colors->links() }}</div>@endif</div>
</div></section>
@endsection
