@php($selectedRole = old('role', $user?->getRoleNames()->first() ?? 'shop_owner'))
@php($selectedModules = old('modules', $user ? $user->enabledModules() : ['tailoring', 'clothing']))
<div class="form-row"><div class="form-group col-md-6"><label>Name</label><input name="name" class="form-control" maxlength="255" required value="{{ old('name', $user?->name) }}"></div><div class="form-group col-md-6"><label>Email</label><input type="email" name="email" class="form-control" required value="{{ old('email', $user?->email) }}"></div></div>
<div class="form-row"><div class="form-group col-md-6"><label>{{ $user ? 'New password (optional)' : 'Password' }}</label><input type="password" name="password" class="form-control" minlength="8" {{ $user ? '' : 'required' }} autocomplete="new-password"></div><div class="form-group col-md-6"><label>Account role</label><select name="role" class="form-control" required>@foreach($allRoles as $role)<option value="{{ $role->name }}" @selected($selectedRole===$role->name)>{{ ucwords(str_replace('_',' ',$role->name)) }}</option>@endforeach</select></div></div>
<fieldset class="border rounded p-3"><legend class="w-auto px-2 h6">Client modules</legend><p class="text-muted small">At least one module is required for a shop-owner client. Access is enforced in navigation and on every protected URL.</p><div class="row">
    @foreach([['tailoring','Tailoring System','Customers, measurements, tailoring orders, job stages, tailors, fittings, and delivery.','fa-cut'],['clothing','Clothing Sales & Purchases','Cloth catalog, stock, counter sales, suppliers, purchases, returns, and inventory ledger.','fa-boxes']] as [$key,$title,$description,$icon])
        <div class="col-md-6 mb-2"><label class="card h-100 mb-0 p-3" style="cursor:pointer"><div class="d-flex"><input type="checkbox" name="modules[]" value="{{ $key }}" class="mr-3 mt-1" @checked(in_array($key,$selectedModules,true))><div><strong><i class="fas {{ $icon }} text-primary mr-1"></i> {{ $title }}</strong><div class="small text-muted mt-1">{{ $description }}</div></div></div></label></div>
    @endforeach
</div></fieldset>
