@extends('main')
@section('content')
<section class="main-content"><div class="container-fluid px-3 px-md-4">
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-3"><div><h3 class="mb-1">مالیاتی ڈیش بورڈ</h3><p class="text-muted mb-0">منافع، نقد بہاؤ، گاہک بقایا، سپلائر بقایا، خریداری اور اسٹاک کی مالیت۔</p></div><div><a class="btn btn-outline-success" href="{{ route('admin.financial-reports.export',['section'=>'summary','start_date'=>$report['period']['start'],'end_date'=>$report['period']['end']]) }}">CSV خلاصہ ڈاؤن لوڈ کریں</a></div></div>
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form class="card card-body mb-3" method="GET" action="{{ route('admin.financial-reports.index') }}"><div class="form-row align-items-end"><div class="form-group col-md-4 mb-md-0"><label>شروع تاریخ</label><input type="date" name="start_date" value="{{ $report['period']['start'] }}" class="form-control" required></div><div class="form-group col-md-4 mb-md-0"><label>آخری تاریخ</label><input type="date" name="end_date" value="{{ $report['period']['end'] }}" class="form-control" required></div><div class="col-md-4"><button class="btn btn-primary">مدت لاگو کریں</button> <a class="btn btn-light" href="{{ route('admin.financial-reports.index') }}">موجودہ مہینہ</a></div></div></form>

    <div class="row mb-3">@foreach([
        ['آمدنی',$report['summary']['total_revenue'],'primary'],['مجموعی منافع',$report['summary']['gross_profit'],$report['summary']['gross_profit']>=0?'success':'danger'],
        ['خالص منافع',$report['summary']['net_profit'],$report['summary']['net_profit']>=0?'success':'danger'],['خالص نقد بہاؤ',$report['summary']['net_cash_flow'],$report['summary']['net_cash_flow']>=0?'info':'danger'],
        ['قابل وصول',$report['summary']['receivables'],'warning'],['قابل ادائیگی',$report['summary']['payables'],'danger'],
        ['موجودہ اسٹاک کی مالیت',$report['summary']['inventory_value'],'info'],['مدت کی خریداریاں',$report['summary']['purchases'],'secondary']
    ] as [$label,$amount,$color])<div class="col-6 col-xl-3 mb-2"><div class="card h-100"><div class="card-body py-3"><small class="text-muted">{{ $label }}</small><div class="h5 text-{{ $color }} mb-0">روپے {{ number_format($amount,2) }}</div></div></div></div>@endforeach</div>

    <div class="row">
        <div class="col-lg-7 mb-3"><div class="card h-100"><div class="card-header"><strong>نفع و نقصان</strong> <span class="text-muted">· {{ $report['period']['start'] }} تا {{ $report['period']['end'] }}</span></div><div class="table-responsive"><table class="table table-sm mb-0"><tbody>
            <tr class="table-light"><th colspan="2">آمدنی</th></tr>@foreach($report['revenue'] as $label=>$amount)<tr><td>{{ $label }}</td><td class="text-right">روپے {{ number_format($amount,2) }}</td></tr>@endforeach
            <tr class="table-primary"><th>کل آمدنی</th><th class="text-right">روپے {{ number_format($report['summary']['total_revenue'],2) }}</th></tr>
            <tr class="table-light"><th colspan="2">براہ راست اخراجات</th></tr>@foreach($report['direct_costs'] as $label=>$amount)<tr><td>{{ $label }}</td><td class="text-right">روپے {{ number_format($amount,2) }}</td></tr>@endforeach
            <tr class="table-success"><th>مجموعی منافع</th><th class="text-right">روپے {{ number_format($report['summary']['gross_profit'],2) }}</th></tr>
            <tr class="table-light"><th colspan="2">کاروباری اخراجات</th></tr>@foreach($report['operating_expenses'] as $label=>$amount)<tr><td>{{ $label }}</td><td class="text-right">روپے {{ number_format($amount,2) }}</td></tr>@endforeach
            <tr class="table-{{ $report['summary']['net_profit']>=0?'success':'danger' }}"><th>خالص منافع</th><th class="text-right">روپے {{ number_format($report['summary']['net_profit'],2) }}</th></tr>
        </tbody></table></div></div></div>
        <div class="col-lg-5 mb-3"><div class="card h-100"><div class="card-header"><strong>نقد بہاؤ</strong></div><div class="table-responsive"><table class="table table-sm mb-0"><tbody><tr><td>گاہکوں سے وصولی</td><td class="text-right text-success">روپے {{ number_format($report['summary']['cash_in'],2) }}</td></tr>@foreach($report['cash_out_breakdown'] as $label=>$amount)<tr><td>{{ $label }}</td><td class="text-right text-danger">روپے {{ number_format($amount,2) }}</td></tr>@endforeach<tr class="table-light"><th>کل نقد ادائیگی</th><th class="text-right">روپے {{ number_format($report['summary']['cash_out'],2) }}</th></tr><tr class="table-{{ $report['summary']['net_cash_flow']>=0?'success':'danger' }}"><th>خالص نقد بہاؤ</th><th class="text-right">روپے {{ number_format($report['summary']['net_cash_flow'],2) }}</th></tr></tbody></table></div><div class="card-body border-top"><div class="d-flex justify-content-between"><span>خریداری واپسی</span><strong>روپے {{ number_format($report['summary']['purchase_returns'],2) }}</strong></div><small class="text-muted">خریداری نقد رقم اور اسٹاک کو متاثر کرتی ہے؛ سامان فروخت ہونے تک اسے کاروباری خرچ شمار نہیں کیا جاتا۔</small></div></div></div>
    </div>

    <div class="row">
        <div class="col-lg-6 mb-3"><div class="card h-100">
            <div class="card-header d-flex justify-content-between"><strong>{{ $report['period']['end'] }} تک گاہکوں سے قابل وصول</strong><a href="{{ route('admin.financial-reports.export',['section'=>'receivables','start_date'=>$report['period']['start'],'end_date'=>$report['period']['end']]) }}">CSV</a></div>
            <div class="card-body py-2"><form method="GET" class="form-inline"><input type="hidden" name="start_date" value="{{ $report['period']['start'] }}"><input type="hidden" name="end_date" value="{{ $report['period']['end'] }}"><input type="hidden" name="payables_q" value="{{ $filters['payables_q'] ?? '' }}"><input type="hidden" name="per_page" value="{{ $filters['per_page'] ?? 10 }}"><input name="receivables_q" maxlength="100" value="{{ $filters['receivables_q'] ?? '' }}" class="form-control form-control-sm mr-2 flex-grow-1" placeholder="گاہک یا فون تلاش کریں"><button class="btn btn-sm btn-primary">تلاش کریں</button></form></div>
            <div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>گاہک</th><th>فون</th><th class="text-right">بقایا</th></tr></thead><tbody>@forelse($report['receivables'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['phone'] }}</td><td class="text-right">روپے {{ number_format($row['balance'],2) }}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted">کوئی بقایا قابل وصول رقم نہیں۔</td></tr>@endforelse</tbody></table></div>
            @if($report['receivables']->hasPages())<div class="card-footer">{{ $report['receivables']->links() }}</div>@endif
        </div></div>
        <div class="col-lg-6 mb-3"><div class="card h-100">
            <div class="card-header d-flex justify-content-between"><strong>{{ $report['period']['end'] }} تک سپلائرز کو قابل ادائیگی</strong><a href="{{ route('admin.financial-reports.export',['section'=>'payables','start_date'=>$report['period']['start'],'end_date'=>$report['period']['end']]) }}">CSV</a></div>
            <div class="card-body py-2"><form method="GET" class="form-inline"><input type="hidden" name="start_date" value="{{ $report['period']['start'] }}"><input type="hidden" name="end_date" value="{{ $report['period']['end'] }}"><input type="hidden" name="receivables_q" value="{{ $filters['receivables_q'] ?? '' }}"><select name="per_page" class="form-control form-control-sm mr-2">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" @selected((int)($filters['per_page']??10)===$size)>{{ $size }} قطاریں</option>@endforeach</select><input name="payables_q" maxlength="100" value="{{ $filters['payables_q'] ?? '' }}" class="form-control form-control-sm mr-2 flex-grow-1" placeholder="سپلائر یا فون تلاش کریں"><button class="btn btn-sm btn-primary">تلاش کریں</button></form></div>
            <div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>سپلائر</th><th>فون</th><th class="text-right">بقایا</th></tr></thead><tbody>@forelse($report['payables'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['phone'] }}</td><td class="text-right">روپے {{ number_format($row['balance'],2) }}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted">کوئی بقایا قابل ادائیگی رقم نہیں۔</td></tr>@endforelse</tbody></table></div>
            @if($report['payables']->hasPages())<div class="card-footer">{{ $report['payables']->links() }}</div>@endif
        </div></div>
    </div>
    <div class="alert alert-light border"><strong>رپورٹ کی بنیاد:</strong> منافع آرڈر اور فروخت کی تاریخوں پر، جبکہ نقد بہاؤ درج شدہ ادائیگی کی تاریخوں پر مبنی ہے۔ قابل وصول اور قابل ادائیگی منتخب آخری تاریخ تک کے بقایا جات ہیں۔</div>
</div></section>
@endsection
