@extends('storefront.public.layout')
@section('title', __('storefront.signup.title'))
@section('meta_description', __('storefront.signup.meta_description'))
@section('canonical_url', route('storefront.business.signup'))
@push('styles')
    .business-nav{background:#0b3d2e;color:#fff}.business-nav .nav-brand,.business-nav .nav-link{color:#fff}.business-nav .nav-link{border-color:rgba(255,255,255,.3)}.brand-icon{margin-inline-end:9px;color:#bde8d7}.business-eyebrow{color:#126b4f;font-weight:900}.signup-page{padding:55px 0 75px;background:#edf4f1;min-height:calc(100vh - 70px)}.signup-shell{max-width:900px}.signup-head{text-align:center;margin-bottom:25px}.signup-card{padding:28px}.signup-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.signup-field{display:flex;flex-direction:column;gap:7px}.signup-field.full{grid-column:1/-1}.signup-field label,.module-choice legend{font-weight:850;color:#193c31}.signup-field input,.signup-field select{min-height:48px;border:1px solid #b9cbc4;border-radius:10px;padding:10px 12px;background:#fff;color:#163127}.module-choice{grid-column:1/-1;border:1px solid #d4e1dc;border-radius:12px;padding:15px}.module-options{display:flex;gap:20px;flex-wrap:wrap}.module-options label{font-weight:700}.signup-errors{padding:14px 18px;border-radius:12px;background:#fff0ef;color:#9e2a21;margin-bottom:18px}.signup-submit{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-top:22px}.terms{display:flex;align-items:flex-start;gap:9px;color:var(--muted)}.selected-trial{padding:13px 15px;border-radius:12px;background:#e4f2ec;color:#126b4f;font-weight:850}.signup-note{margin-top:15px;color:var(--muted)}@media(max-width:650px){.signup-grid{grid-template-columns:1fr}.signup-field.full,.module-choice{grid-column:auto}.signup-submit{align-items:stretch;flex-direction:column}.signup-card{padding:20px}}
@endpush
@section('body')
<nav class="nav business-nav"><div class="shell"><a class="nav-brand" href="{{ route('storefront.business') }}"><i class="fas fa-cut brand-icon"></i>BuyNStitch</a><div class="nav-actions">@include('storefront.public.partials.language-switch')<a class="nav-link" href="{{ route('login') }}">{{ __('storefront.common.business_login') }}</a></div></div></nav>
<main class="signup-page"><div class="shell signup-shell"><div class="signup-head"><div class="business-eyebrow">{{ __('storefront.signup.eyebrow') }}</div><h1>{{ __('storefront.signup.heading') }}</h1><p class="muted">{{ __('storefront.signup.intro') }}</p></div>
@if($errors->any())<div class="signup-errors"><strong>{{ __('storefront.signup.fix_errors') }}</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($plans->isEmpty())<div class="card signup-card"><h2>{{ __('storefront.signup.unavailable_title') }}</h2><p>{{ __('storefront.signup.unavailable_text') }}</p><a class="btn" href="{{ route('storefront.business') }}">{{ __('storefront.signup.back') }}</a></div>@else
<form class="card signup-card" method="POST" action="{{ route('storefront.business.signup.store') }}">@csrf<div class="signup-grid">
<div class="signup-field full"><label for="subscription_plan_id">{{ __('storefront.signup.plan') }}</label><select id="subscription_plan_id" name="subscription_plan_id" required>@foreach($plans as $plan)<option value="{{ $plan->id }}" data-tailoring="{{ $plan->allow_tailoring ? 1 : 0 }}" data-clothing="{{ $plan->allow_clothing ? 1 : 0 }}" data-trial="{{ $plan->trial_days }}" @selected((int) old('subscription_plan_id', $selectedPlan) === $plan->id)>{{ $plan->name }} — Rs {{ number_format((float)$plan->price) }} — {{ $plan->trial_days }} {{ __('storefront.common.days') }}</option>@endforeach</select><div id="trial-summary" class="selected-trial"></div></div>
<div class="signup-field"><label for="owner_name">{{ __('storefront.signup.owner_name') }}</label><input id="owner_name" name="owner_name" required maxlength="255" value="{{ old('owner_name') }}"></div>
<div class="signup-field"><label for="business_name">{{ __('storefront.signup.business_name') }}</label><input id="business_name" name="business_name" required maxlength="255" value="{{ old('business_name') }}"></div>
<div class="signup-field"><label for="email">{{ __('storefront.common.email') }}</label><input id="email" type="email" name="email" required maxlength="255" autocomplete="email" value="{{ old('email') }}"></div>
<div class="signup-field"><label for="mobile">{{ __('storefront.signup.mobile') }}</label><input id="mobile" name="mobile" required maxlength="30" inputmode="tel" placeholder="03001234567" value="{{ old('mobile') }}"></div>
<fieldset class="module-choice"><legend>{{ __('storefront.signup.modules') }}</legend><div class="module-options"><label><input class="module-check" data-module="tailoring" type="checkbox" name="modules[]" value="tailoring" @checked(in_array('tailoring', old('modules', []), true))> {{ __('storefront.common.tailoring') }}</label><label><input class="module-check" data-module="clothing" type="checkbox" name="modules[]" value="clothing" @checked(in_array('clothing', old('modules', []), true))> {{ __('storefront.common.clothing') }}</label></div></fieldset>
<div class="signup-field"><label for="password">{{ __('storefront.signup.password') }}</label><input id="password" type="password" name="password" required minlength="8" autocomplete="new-password"></div>
<div class="signup-field"><label for="password_confirmation">{{ __('storefront.signup.password_confirmation') }}</label><input id="password_confirmation" type="password" name="password_confirmation" required minlength="8" autocomplete="new-password"></div>
</div><div class="signup-submit"><label class="terms"><input type="checkbox" name="terms" value="1" required> <span>{{ __('storefront.signup.terms') }}</span></label><button class="btn" type="submit">{{ __('storefront.signup.submit') }}</button></div><p class="signup-note">{{ __('storefront.signup.verification_note') }}</p></form>@endif
</div></main>
@if($plans->isNotEmpty())@push('scripts')<script>(function(){const plan=document.getElementById('subscription_plan_id');const summary=document.getElementById('trial-summary');function applyPlan(){const selected=plan.options[plan.selectedIndex];const trial=selected.dataset.trial;summary.textContent=@json(__('storefront.signup.trial_summary')).replace(':days',trial);document.querySelectorAll('.module-check').forEach(function(input){const allowed=selected.dataset[input.dataset.module]==='1';input.disabled=!allowed;if(!allowed)input.checked=false;});const enabled=[...document.querySelectorAll('.module-check:not(:disabled)')];if(enabled.length===1)enabled[0].checked=true;}plan.addEventListener('change',applyPlan);applyPlan();})();</script>@endpush @endif
@endsection
