@extends('storefront.public.layout')
@section('title', __('storefront.business.title'))
@section('meta_description', __('storefront.business.meta_description'))
@section('canonical_url', route('storefront.business'))
@push('structured_data')
<script type="application/ld+json">{!! \App\Support\StorefrontSeo::json([
    '@context' => 'https://schema.org',
    '@type' => 'WebPage',
    '@id' => route('storefront.business').'#webpage',
    'url' => route('storefront.business'),
    'name' => __('storefront.business.title'),
    'description' => __('storefront.business.meta_description'),
    'inLanguage' => app()->getLocale(),
]) !!}</script>
@endpush
@push('styles')
    .business-nav{background:#0b3d2e;color:#fff}.business-nav .nav-brand,.business-nav .nav-link{color:#fff}.business-nav .nav-link{border-color:rgba(255,255,255,.3)}.brand-icon{margin-inline-end:9px;color:#bde8d7}
    .business-hero{padding:82px 0;background:radial-gradient(circle at 85% 25%,rgba(61,190,143,.4),transparent 28%),linear-gradient(135deg,#082f24,#126b4f);color:#fff}.business-hero-grid{display:grid;grid-template-columns:1.25fr .75fr;align-items:center;gap:48px}.business-eyebrow{color:#bde8d7;font-weight:900}.business-hero h1{max-width:850px;font-size:clamp(2.25rem,5vw,4.4rem);line-height:1.22;margin:10px 0 18px}.business-hero p{max-width:760px;color:#d8eee5;font-size:1.05rem}.hero-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:25px}.hero-actions .btn-primary-light{background:#fff;color:#0b4937;font-weight:900}.hero-actions .btn-outline{border:1px solid rgba(255,255,255,.55);background:transparent;color:#fff}.hero-panel{padding:25px;border:1px solid rgba(255,255,255,.2);border-radius:20px;background:rgba(255,255,255,.09)}.hero-promise{display:flex;align-items:center;gap:12px;padding:14px 0;color:#e7f5ef}.hero-promise+.hero-promise{border-top:1px solid rgba(255,255,255,.15)}.hero-promise i{display:grid;place-items:center;width:40px;height:40px;border-radius:11px;background:#fff;color:#126b4f}
    .business-section{padding:64px 0}.business-section.soft{background:#edf4f1}.section-head{max-width:780px;margin:0 auto 30px;text-align:center}.section-head h2{margin:0;font-size:clamp(1.7rem,3vw,2.55rem)}.section-head p{margin:8px 0 0}.audience-grid,.feature-grid,.workflow-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.audience-card{border-top:4px solid #126b4f}.audience-icon,.feature-icon{display:grid;place-items:center;width:50px;height:50px;margin-bottom:16px;border-radius:14px;background:#e4f2ec;color:#126b4f;font-size:1.15rem}.audience-card h3,.feature-card h3,.workflow-card h3{margin:0 0 7px}.audience-card p,.feature-card p,.workflow-card p{margin:0;color:var(--muted)}
    .feature-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.feature-card{box-shadow:none}.workflow-card{position:relative;padding-top:62px}.workflow-number{position:absolute;top:19px;inset-inline-start:20px;display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:#126b4f;color:#fff;font:900 1rem Arial}
    .value-section{background:#0b3d2e;color:#fff}.value-section .section-head h2{color:#fff}.value-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.value-item{display:grid;grid-template-columns:44px 1fr;gap:14px;padding:20px;border:1px solid rgba(255,255,255,.16);border-radius:16px;background:rgba(255,255,255,.07)}.value-item i{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;background:#fff;color:#126b4f}.value-item h3{margin:0 0 4px;color:#fff}.value-item p{margin:0;color:#cfe5dc}
    .start-card{display:flex;align-items:center;justify-content:space-between;gap:28px;padding:38px;border-radius:20px;background:#e1f1ea}.start-card h2{margin:0}.start-card p{max-width:760px;margin:7px 0 0}.start-actions{display:flex;flex-direction:column;gap:9px;min-width:230px}.start-actions .btn-secondary{border:1px solid #99b9ac;background:#fff;color:#126b4f}
    @media(max-width:900px){.business-hero-grid{grid-template-columns:1fr}.hero-panel{display:none}.audience-grid,.feature-grid{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:650px){.business-hero{padding:55px 0}.business-section{padding:45px 0}.audience-grid,.feature-grid,.workflow-grid,.value-grid{grid-template-columns:1fr}.start-card{align-items:start;flex-direction:column}.start-actions{width:100%;min-width:0}}
@endpush
@section('body')
<nav class="nav business-nav"><div class="shell"><a class="nav-brand" href="{{ route('storefront.index') }}"><i class="fas fa-cut brand-icon"></i>BuyNStitch <span style="font-weight:400;margin-inline-start:7px">{{ __('storefront.marketplace.services_nav') }}</span></a><div class="nav-actions">@include('storefront.public.partials.language-switch')<a class="nav-link" href="{{ route('storefront.index') }}">{{ __('storefront.business.nav_marketplace') }}</a><a class="nav-link" href="{{ route('login') }}">{{ __('storefront.common.business_login') }}</a></div></div></nav>

<header class="business-hero"><div class="shell business-hero-grid"><div><div class="business-eyebrow">{{ __('storefront.business.eyebrow') }}</div><h1>{{ __('storefront.business.hero_title') }}</h1><p>{{ __('storefront.business.hero_text') }}</p><div class="hero-actions"><a class="btn btn-primary-light" href="#features">{{ __('storefront.business.hero_primary') }}</a><a class="btn btn-outline" href="{{ route('login') }}">{{ __('storefront.business.hero_login') }}</a></div></div><aside class="hero-panel" aria-label="{{ __('storefront.business.nav_features') }}">@foreach([['fa-user-check','promise_one'],['fa-store','promise_two'],['fa-shopping-bag','promise_three']] as [$icon,$text])<div class="hero-promise"><i class="fas {{ $icon }}"></i><strong>{{ __('storefront.business.'.$text) }}</strong></div>@endforeach</aside></div></header>

<main>
<section class="business-section"><div class="shell"><div class="section-head"><h2>{{ __('storefront.business.audience_title') }}</h2><p class="muted">{{ __('storefront.business.audience_text') }}</p></div><div class="audience-grid">@foreach([['fa-boxes','cloth_title','cloth_text'],['fa-cut','tailor_title','tailor_text'],['fa-store-alt','combined_title','combined_text']] as [$icon,$title,$text])<article class="card audience-card"><span class="audience-icon"><i class="fas {{ $icon }}"></i></span><h3>{{ __('storefront.business.'.$title) }}</h3><p>{{ __('storefront.business.'.$text) }}</p></article>@endforeach</div></div></section>

<section class="business-section soft" id="features"><div class="shell"><div class="section-head"><h2>{{ __('storefront.business.features_title') }}</h2><p class="muted">{{ __('storefront.business.features_text') }}</p></div><div class="feature-grid">@foreach([['fa-globe-asia','feature_storefront_title','feature_storefront_text'],['fa-cut','feature_tailoring_title','feature_tailoring_text'],['fa-boxes','feature_inventory_title','feature_inventory_text'],['fa-user-circle','feature_customer_title','feature_customer_text'],['fa-wifi','feature_offline_title','feature_offline_text'],['fa-users-cog','feature_team_title','feature_team_text']] as [$icon,$title,$text])<article class="card feature-card"><span class="feature-icon"><i class="fas {{ $icon }}"></i></span><h3>{{ __('storefront.marketplace.'.$title) }}</h3><p>{{ __('storefront.marketplace.'.$text) }}</p></article>@endforeach</div></div></section>

<section class="business-section"><div class="shell"><div class="section-head"><h2>{{ __('storefront.business.workflow_title') }}</h2></div><div class="workflow-grid">@foreach([['workflow_one_title','workflow_one_text'],['workflow_two_title','workflow_two_text'],['workflow_three_title','workflow_three_text']] as [$title,$text])<article class="card workflow-card"><span class="workflow-number">{{ $loop->iteration }}</span><h3>{{ __('storefront.business.'.$title) }}</h3><p>{{ __('storefront.business.'.$text) }}</p></article>@endforeach</div></div></section>

<section class="business-section value-section"><div class="shell"><div class="section-head"><h2>{{ __('storefront.business.value_title') }}</h2></div><div class="value-grid">@foreach([['fa-clipboard-check','value_one_title','value_one_text'],['fa-chart-line','value_two_title','value_two_text'],['fa-smile','value_three_title','value_three_text'],['fa-wifi','value_four_title','value_four_text']] as [$icon,$title,$text])<article class="value-item"><i class="fas {{ $icon }}"></i><div><h3>{{ __('storefront.business.'.$title) }}</h3><p>{{ __('storefront.business.'.$text) }}</p></div></article>@endforeach</div></div></section>

<section class="business-section"><div class="shell"><div class="start-card"><div><h2>{{ __('storefront.business.start_title') }}</h2><p class="muted">{{ __('storefront.business.start_text') }}</p></div><div class="start-actions"><a class="btn" href="{{ route('login') }}">{{ __('storefront.business.start_login') }}</a><a class="btn btn-secondary" href="{{ route('storefront.index') }}">{{ __('storefront.business.back_marketplace') }}</a></div></div></div></section>
</main>
<footer class="footer"><div class="shell">{{ __('storefront.business.footer') }} · © {{ now()->year }}</div></footer>
@endsection
