@extends('storefront.public.layout')
@section('title', __('storefront.cart.title').' — '.$storefront->display_name)
@section('meta_description', __('storefront.cart.intro'))
@section('canonical_url', route('storefront.cart.show',$storefront))
@section('robots', 'noindex,nofollow')
@push('styles')
.item{display:grid;grid-template-columns:1fr auto;gap:14px;border-bottom:1px solid var(--line);padding:15px 0}.controls{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.controls form{display:flex;gap:7px}.controls .control{max-width:130px}.total{display:flex;justify-content:space-between;font-size:1.2rem;font-weight:900}.choice{display:block;border:1px solid #c9d8d1;border-radius:12px;padding:10px 12px;margin:7px 0;background:#f8fbfa}.payment-extra,.payment-instructions{background:#fff8df;border:1px solid #ead79c;border-radius:12px;padding:12px;margin-top:10px}.payment-instructions div{margin-top:5px}.raast-payment-qr{display:block;width:min(220px,100%);height:auto;margin:12px auto 0;border-radius:10px}@media(max-width:600px){.item{grid-template-columns:1fr}}
@endpush
@section('body')
<nav class="nav"><div class="shell"><a class="nav-brand" href="{{ route('storefront.show',$storefront) }}">{{ $storefront->display_name }}</a><div class="nav-actions">@include('storefront.public.partials.language-switch')<a class="nav-link" href="{{ route('storefront.clothing.index',$storefront) }}">{{ __('storefront.cart.continue') }}</a></div></div></nav>
<header class="hero"><div class="shell"><h1>{{ __('storefront.cart.title') }}</h1><p>{{ __('storefront.cart.intro') }}</p></div></header>
<main class="section"><div class="shell">@if(session('success'))<div class="success">{{ session('success') }}</div>@endif @if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
<div class="two-col"><section class="card">
@forelse($cart?->items ?? [] as $item)<article class="item"><div><h2>{{ $item->listing->display_name }}</h2><div class="muted">{{ $item->color->color }} · {!! \App\Support\PakistanCurrency::html($item->unit_price_snapshot) !!} {{ __('storefront.clothing.per_metre') }}</div><div class="price">{!! \App\Support\PakistanCurrency::html($item->line_total) !!}</div><small>{{ __('storefront.cart.reserved_until',['time'=>$item->reserved_until->format('h:i A')]) }}</small></div><div class="controls"><form method="POST" action="{{ route('storefront.cart.update',[$storefront,$item->id]) }}">@csrf @method('PATCH')<input class="control" type="number" name="quantity" min="{{ $item->listing->minimumOrderQuantity() }}" max="{{ $item->listing->maximumOrderQuantity() }}" step="{{ $item->listing->orderIncrement() }}" value="{{ $item->quantity }}" aria-label="{{ __('storefront.clothing.quantity_label') }}"><button class="btn">{{ __('storefront.cart.update') }}</button></form><form method="POST" action="{{ route('storefront.cart.destroy',[$storefront,$item->id]) }}">@csrf @method('DELETE')<button class="btn btn-danger">{{ __('storefront.cart.remove') }}</button></form></div></article>
@empty<div class="empty"><h2>{{ __('storefront.cart.empty_title') }}</h2><p class="muted">{{ __('storefront.cart.empty_text') }}</p><a class="btn" href="{{ route('storefront.clothing.index',$storefront) }}">{{ __('storefront.cart.browse') }}</a></div>@endforelse
@if($cart && $cart->items->isNotEmpty())<div class="total"><span>{{ __('storefront.cart.estimated_total') }}</span><span>{!! \App\Support\PakistanCurrency::html($cart->items->sum(fn($item)=>$item->line_total)) !!}</span></div><div class="notice" style="margin-top:14px">{{ __('storefront.cart.reservation_notice') }}</div>
@if($cart->customer)<form method="POST" action="{{ route('storefront.checkout.store',$storefront) }}" enctype="multipart/form-data" style="margin-top:20px">@csrf<h2>{{ __('storefront.cart.checkout_title') }}</h2><p class="muted">{{ __('storefront.cart.checkout_explainer') }}</p>
<div class="form-group"><label>{{ __('storefront.cart.fulfillment') }}</label>@if($storefront->clothingPickupEnabled())<label class="choice"><input type="radio" name="fulfillment_method" value="pickup" @checked(old('fulfillment_method','pickup')==='pickup')> {{ __('storefront.cart.pickup') }}</label>@endif @if($storefront->clothingDeliveryEnabled())<label class="choice"><input type="radio" name="fulfillment_method" value="delivery" @checked(old('fulfillment_method')==='delivery')> {{ __('storefront.cart.delivery') }}</label>@endif</div>
@if($storefront->clothingDeliveryEnabled())<div class="form-group"><label for="delivery_address">{{ __('storefront.cart.delivery_address') }}</label><textarea id="delivery_address" name="delivery_address" class="control" rows="3" maxlength="1000">{{ old('delivery_address') }}</textarea></div>@endif
@php
    $acceptedPaymentMethods = $storefront->acceptedPaymentMethods();
    $hasManualPaymentMethod = collect(array_keys($acceptedPaymentMethods))
        ->contains(fn ($method) => \App\Models\StorefrontOrder::requiresManualVerification($method));
@endphp
<div class="form-group"><label>{{ __('storefront.cart.payment_method') }}</label>@foreach($acceptedPaymentMethods as $value=>$label)<label class="choice"><input type="radio" name="payment_method" value="{{ $value }}" @checked(old('payment_method',array_key_first($acceptedPaymentMethods))===$value)> {{ $label }}</label>@endforeach
@if($hasManualPaymentMethod)
<small class="muted">{{ __('storefront.cart.manual_payment_help') }}</small>
@include('storefront.public.partials.payment-instructions')
<div id="manual-order-fields" class="payment-extra"><div id="payment-sender-phone-group" class="form-group"><label for="payment_sender_phone">{{ __('storefront.cart.sender_phone') }}</label><input id="payment_sender_phone" name="payment_sender_phone" dir="ltr" class="control" maxlength="50" value="{{ old('payment_sender_phone') }}"></div><div class="form-group"><label for="payment_reference">{{ __('storefront.cart.payment_reference') }}</label><input id="payment_reference" name="payment_reference" dir="ltr" class="control" maxlength="100" value="{{ old('payment_reference') }}"></div><div class="form-group"><label for="payment_evidence">{{ __('storefront.cart.payment_evidence') }}</label><input id="payment_evidence" name="payment_evidence" type="file" class="control" accept=".jpg,.jpeg,.png,.webp,.pdf"><small class="muted">{{ __('storefront.cart.payment_evidence_help') }}</small></div></div>
@endif
</div>
<div class="form-group"><label for="customer_note">{{ __('storefront.cart.customer_note') }}</label><textarea id="customer_note" name="customer_note" class="control" rows="3" maxlength="1000">{{ old('customer_note') }}</textarea></div>
@if($storefront->clothingPickupEnabled() || $storefront->clothingDeliveryEnabled())<button class="btn" style="width:100%">{{ __('storefront.cart.submit') }}</button>@else<div class="errors">{{ __('storefront.cart.no_fulfillment') }}</div>@endif</form>
@else<div class="notice">{{ __('storefront.cart.link_first') }}</div>@endif @endif
</section>
<aside class="card"><h2>{{ __('storefront.cart.customer_identity') }}</h2>@if($cart?->customer)<div class="notice"><strong>{{ $cart->customer->name }}</strong><div dir="ltr">{{ $cart->customer->phone_number1 }}</div><p>{{ __('storefront.cart.linked_record') }}</p><form method="POST" action="{{ route('storefront.cart.customer.unlink',$storefront) }}">@csrf @method('DELETE')<button class="btn">{{ __('storefront.cart.unlink') }}</button></form></div>
@elseif($cart && $cart->items->isNotEmpty())<h3>{{ __('storefront.cart.existing_customer') }}</h3><p class="muted">{{ __('storefront.cart.existing_help') }}</p><form method="POST" action="{{ route('storefront.cart.customer.link',$storefront) }}">@csrf<div class="form-group"><label for="cart_phone">{{ __('storefront.common.phone') }}</label><input id="cart_phone" name="phone" type="tel" inputmode="tel" dir="ltr" class="control" required maxlength="50" placeholder="{{ __('storefront.common.phone_placeholder') }}"></div><div class="form-group"><label for="cart_pin">{{ __('storefront.cart.pin') }}</label><input id="cart_pin" name="pin" type="password" dir="ltr" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" class="control" required></div><button class="btn" style="width:100%">{{ __('storefront.cart.link_record') }}</button></form>
<hr style="margin:24px 0;border:0;border-top:1px solid var(--line)">
<h3>{{ __('storefront.cart.new_customer') }}</h3><p class="muted">{{ __('storefront.cart.new_customer_help') }}</p><form method="POST" action="{{ route('storefront.cart.customer.register',$storefront) }}">@csrf<div class="form-group"><label for="register_name">{{ __('storefront.cart.customer_name') }}</label><input id="register_name" name="name" class="control" required maxlength="150" value="{{ old('name') }}" autocomplete="name"></div><div class="form-group"><label for="register_phone">{{ __('storefront.common.phone') }}</label><input id="register_phone" name="phone" type="tel" inputmode="tel" dir="ltr" class="control" required maxlength="50" placeholder="{{ __('storefront.common.phone_placeholder') }}" value="{{ old('phone') }}" autocomplete="tel"></div><div class="form-group"><label for="register_pin">{{ __('storefront.cart.choose_pin') }}</label><input id="register_pin" name="pin" type="password" dir="ltr" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" class="control" required autocomplete="new-password"></div><div class="form-group"><label for="register_pin_confirmation">{{ __('storefront.cart.confirm_pin') }}</label><input id="register_pin_confirmation" name="pin_confirmation" type="password" dir="ltr" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" class="control" required autocomplete="new-password"></div><div class="notice">{{ __('storefront.cart.unverified_note') }}</div><button class="btn" style="width:100%;margin-top:12px">{{ __('storefront.cart.register') }}</button></form>
@else<p class="muted">{{ __('storefront.cart.add_first') }}</p>@endif</aside></div></div></main>
@endsection
@push('scripts')
<script>(()=>{const manual=@json(\App\Models\StorefrontOrder::manualPaymentMethods()),wallets=['easypaisa','jazzcash'],fields=document.getElementById('manual-order-fields'),senderGroup=document.getElementById('payment-sender-phone-group'),sender=document.getElementById('payment_sender_phone'),reference=document.getElementById('payment_reference');const refresh=()=>{const method=document.querySelector('input[name="payment_method"]:checked')?.value,visible=manual.includes(method),wallet=wallets.includes(method);if(fields)fields.hidden=!visible;if(senderGroup)senderGroup.hidden=!wallet;if(sender)sender.required=wallet;if(reference)reference.required=visible;document.querySelectorAll('[data-payment-instructions]').forEach(panel=>panel.hidden=panel.dataset.paymentInstructions!==method)};document.querySelectorAll('input[name="payment_method"]').forEach(input=>input.addEventListener('change',refresh));refresh()})()</script>
@endpush
