@extends('storefront.public.layout')
@section('title', __('storefront.marketplace.title'))
@section('meta_description', __('storefront.marketplace.hero_text'))
@section('canonical_url', route('storefront.index'))
@push('structured_data')
@php
    $marketplaceItems = $topStorefronts->map(fn ($storefront, $index) => [
        '@type' => 'ListItem',
        'position' => $index + 1,
        'name' => $storefront->display_name,
        'url' => route('storefront.show', $storefront),
    ])->values()->all();
@endphp
<script type="application/ld+json">{!! \App\Support\StorefrontSeo::json(\App\Support\StorefrontSeo::graph(
    \App\Support\StorefrontSeo::website(
        __('storefront.common.marketplace'),
        __('storefront.marketplace.hero_text'),
        route('storefront.index')
    ),
    $marketplaceItems ? [
        '@type' => 'ItemList',
        '@id' => route('storefront.index').'#top-stores',
        'name' => __('storefront.marketplace.top_stores'),
        'itemListElement' => $marketplaceItems,
    ] : []
)) !!}</script>
@endpush
@push('styles')
    .market-nav{background:#0b3d2e;color:#fff}.market-nav .nav-brand,.market-nav .nav-link{color:#fff}.market-nav .nav-link{border-color:rgba(255,255,255,.3)}
    .brand-icon{margin-inline-end:9px;color:#bde8d7}.market-hero{padding:70px 0 92px;background:radial-gradient(circle at 15% 20%,#2ca679 0,transparent 28%),linear-gradient(135deg,#0b3d2e,#126f50)}.market-hero h1{max-width:850px}.market-hero p{max-width:760px;font-size:1.05rem}.hero-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}.hero-actions .btn{background:#fff;color:#0b4937;font-weight:900}.hero-actions .btn-outline{border:1px solid rgba(255,255,255,.55);background:transparent;color:#fff}
    .market-filters{position:relative;margin:-36px auto 38px;padding:22px}.market-filter-grid{display:grid;grid-template-columns:1.5fr .85fr 1.15fr 1.15fr auto;gap:12px;align-items:end}.filter-field label{display:block;margin-bottom:6px;font-size:.82rem;font-weight:800}.filter-actions{display:flex;gap:8px}
    .market-section{padding:48px 0}.market-section.soft{background:#edf4f1}.section-head{display:flex;align-items:end;justify-content:space-between;gap:22px;margin-bottom:22px}.section-head h2{margin:0;font-size:clamp(1.55rem,3vw,2.25rem)}.section-head p{max-width:720px;margin:5px 0 0}.section-link{color:var(--primary);font-weight:900;text-decoration:none;white-space:nowrap}
    .market-stats{display:flex;gap:12px;flex-wrap:wrap;margin-top:20px}.market-stat{padding:8px 14px;border:1px solid rgba(255,255,255,.28);border-radius:999px;background:rgba(255,255,255,.1)}.market-stat strong{margin-inline-end:5px;font-family:Arial,sans-serif}
    .shop-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.shop{position:relative;padding:0;overflow:hidden;display:flex;flex-direction:column}.cover{height:170px;background:linear-gradient(135deg,#d9efe6,#9ed7c0);background-size:cover;background-position:center}.cover-placeholder{height:100%;display:grid;place-items:center;color:#147053;font-size:2.4rem}.shop-rank{position:absolute;top:13px;inset-inline-start:13px;display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:#fff;color:#0b6047;font:900 1rem Arial;box-shadow:0 5px 18px rgba(0,0,0,.15)}.shop-body{padding:20px;display:flex;flex-direction:column;flex:1}.shop-body h3{margin:0}.shop-city{color:var(--muted);font-size:.9rem}.tags{display:flex;flex-wrap:wrap;gap:7px;margin:12px 0}.shop .btn{margin-top:auto}
    .product-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.product{padding:0;overflow:hidden}.product-image{position:relative;height:205px;display:grid;place-items:center;background:#deeee7;color:#147053;font-size:2.5rem;text-decoration:none}.product-image img{width:100%;height:100%;object-fit:cover}.product-badge{position:absolute;top:12px;inset-inline-start:12px;padding:4px 9px;border-radius:999px;background:#fff;color:#126b4f;font-size:.75rem;font-weight:900}.product-body{padding:18px}.product-body h3{margin:0 0 5px;font-size:1rem}.product-shop{color:var(--muted);font-size:.83rem}.product-price{margin-top:12px;font-weight:900}
    .steps{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.step-number{display:grid;place-items:center;width:38px;height:38px;margin-bottom:13px;border-radius:50%;background:#126b4f;color:#fff;font:900 1rem Arial}.step h3{margin:0 0 5px}.step p{margin:0}
    .business-cta{display:flex;align-items:center;justify-content:space-between;gap:25px;padding:30px;border-radius:18px;background:#e1f1ea}.business-cta h2{margin:0}.business-cta p{margin:5px 0 0}.faq-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.faq{padding:18px}.faq summary{cursor:pointer;font-weight:900}.faq p{margin:10px 0 0}
    @media(max-width:950px){.market-filter-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.filter-actions{grid-column:1/-1}.product-grid{grid-template-columns:repeat(2,1fr)}.shop-grid{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:650px){.market-hero{padding:50px 0 72px}.market-filter-grid,.shop-grid,.product-grid,.steps,.faq-grid{grid-template-columns:1fr}.section-head,.business-cta{align-items:start;flex-direction:column}.market-section{padding:38px 0}.market-filters{margin-top:-28px}.filter-actions .btn{flex:1}}
@endpush
@section('body')
<nav class="nav market-nav"><div class="shell"><a class="nav-brand" href="{{ route('storefront.index') }}"><i class="fas fa-cut brand-icon"></i>BuyNStitch</a><div class="nav-actions">@include('storefront.public.partials.language-switch')<a class="nav-link" href="{{ route('storefront.business') }}">{{ __('storefront.marketplace.services_nav') }}</a><a class="nav-link" href="{{ route('login') }}">{{ __('storefront.common.business_login') }}</a></div></div></nav>

<header class="hero market-hero"><div class="shell"><div class="muted" style="color:#bde8d7;font-weight:900">{{ __('storefront.marketplace.hero_eyebrow') }}</div><h1>{{ __('storefront.marketplace.hero_title') }}</h1><p>{{ __('storefront.marketplace.hero_text') }}</p><div class="hero-actions"><a class="btn" href="#stores">{{ __('storefront.marketplace.hero_primary') }}</a><a class="btn btn-outline" href="{{ route('storefront.business') }}">{{ __('storefront.marketplace.services_nav') }}</a></div><div class="market-stats"><span class="market-stat"><strong>{{ number_format($marketplaceStats['shops']) }}</strong>{{ __('storefront.marketplace.stat_shops') }}</span><span class="market-stat"><strong>{{ number_format($marketplaceStats['products']) }}</strong>{{ __('storefront.marketplace.stat_products') }}</span><span class="market-stat"><strong>{{ number_format($marketplaceStats['services']) }}</strong>{{ __('storefront.marketplace.stat_services') }}</span></div></div></header>

<main>
<div class="shell" id="stores"><form class="card market-filters" method="GET"><div class="market-filter-grid"><div class="filter-field"><label for="market_q">{{ __('storefront.marketplace.search_label') }}</label><input id="market_q" class="control" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="{{ __('storefront.marketplace.search_placeholder') }}"></div><div class="filter-field"><label for="market_city">{{ __('storefront.marketplace.city_label') }}</label><select id="market_city" class="control" name="city"><option value="">{{ __('storefront.marketplace.all_cities') }}</option>@foreach($cities as $city)<option value="{{ $city }}" @selected(($filters['city']??'')===$city)>{{ $city }}</option>@endforeach</select></div><div class="filter-field"><label for="market_category">{{ __('storefront.marketplace.category_label') }}</label><select id="market_category" class="control" name="category"><option value="">{{ __('storefront.marketplace.all_categories') }}</option><option value="clothing" @selected(($filters['category']??'')==='clothing')>{{ __('storefront.common.clothing') }}</option><option value="tailoring" @selected(($filters['category']??'')==='tailoring')>{{ __('storefront.common.tailoring') }}</option><option value="both" @selected(($filters['category']??'')==='both')>{{ __('storefront.marketplace.both_categories') }}</option></select></div><div class="filter-field"><label for="market_delivery">{{ __('storefront.marketplace.delivery_label') }}</label><select id="market_delivery" class="control" name="delivery"><option value="">{{ __('storefront.marketplace.any_delivery') }}</option><option value="1" @selected(($filters['delivery']??'')==='1')>{{ __('storefront.marketplace.delivery_available') }}</option></select></div><div class="filter-actions"><button class="btn">{{ __('storefront.marketplace.apply_filters') }}</button>@if(collect($filters)->contains(fn($value)=>$value!==null && $value!==''))<a class="btn btn-secondary" href="{{ route('storefront.index') }}#stores">{{ __('storefront.marketplace.clear_filters') }}</a>@endif</div></div></form></div>

@if($topStorefronts->isNotEmpty())
<section class="market-section"><div class="shell"><div class="section-head"><div><h2>{{ __('storefront.marketplace.top_stores') }}</h2><p class="muted">{{ __('storefront.marketplace.top_stores_text') }}</p></div><a class="section-link" href="#all-stores">{{ __('storefront.common.all_shops') }}</a></div><div class="shop-grid">@foreach($topStorefronts as $storefront)<article class="card shop"><div class="cover" @if($storefront->cover_url) style="background-image:url('{{ $storefront->cover_url }}')" @endif>@unless($storefront->cover_url)<div class="cover-placeholder"><i class="fas fa-store-alt"></i></div>@endunless</div><span class="shop-rank">{{ $loop->iteration }}</span><div class="shop-body"><h3>{{ $storefront->display_name }}</h3><div class="shop-city"><i class="fas fa-map-marker-alt"></i> {{ $storefront->city ?: __('storefront.common.pakistan') }}</div><p>{{ $storefront->tagline ?: __('storefront.marketplace.default_tagline') }}</p><div class="tags">@if($storefront->show_clothing && $storefront->business->clothing_enabled)<span class="pill">{{ __('storefront.common.clothing') }}</span>@endif @if($storefront->show_tailoring && $storefront->business->tailoring_enabled)<span class="pill">{{ __('storefront.common.tailoring') }}</span>@endif @if($storefront->offersDelivery())<span class="pill">{{ __('storefront.common.delivery') }}</span>@endif</div><a class="btn" href="{{ route('storefront.show',$storefront) }}">{{ __('storefront.marketplace.view_shop') }}</a></div></article>@endforeach</div></div></section>
@endif

@if($topProducts->isNotEmpty())
<section class="market-section soft" id="top-products"><div class="shell"><div class="section-head"><div><h2>{{ __('storefront.marketplace.top_products') }}</h2><p class="muted">{{ __('storefront.marketplace.top_products_text') }}</p></div></div><div class="product-grid">@foreach($topProducts as $listing)@php($image = $listing->cloth?->images?->first(fn ($item) => $item->image_url))<article class="card product"><a class="product-image" href="{{ route('storefront.clothing.show', [$listing->storefront, $listing]) }}">@if($image)<img src="{{ $image->image_url }}" alt="{{ $listing->display_name }}" loading="lazy">@else<i class="fas fa-tshirt"></i>@endif @if($listing->is_featured)<span class="product-badge">{{ __('storefront.common.featured') }}</span>@endif</a><div class="product-body"><h3>{{ $listing->display_name }}</h3><div class="product-shop">{{ __('storefront.marketplace.product_shop',['shop'=>$listing->storefront->display_name]) }}</div><div class="product-price">{!! \App\Support\PakistanCurrency::html($listing->cloth?->sale_price ?: $listing->cloth?->price) !!} <small class="muted">/{{ __('storefront.common.metre') }}</small></div><a class="btn" style="width:100%;margin-top:13px" href="{{ route('storefront.clothing.show', [$listing->storefront, $listing]) }}">{{ __('storefront.marketplace.view_product') }}</a></div></article>@endforeach</div></div></section>
@endif

<section class="market-section soft"><div class="shell"><div class="section-head"><div><h2>{{ __('storefront.marketplace.how_title') }}</h2></div></div><div class="steps">@foreach([['how_find_title','how_find_text'],['how_choose_title','how_choose_text'],['how_order_title','how_order_text']] as [$title,$text])<article class="card step"><span class="step-number">{{ $loop->iteration }}</span><h3>{{ __('storefront.marketplace.'.$title) }}</h3><p class="muted">{{ __('storefront.marketplace.'.$text) }}</p></article>@endforeach</div></div></section>

<section class="market-section" id="all-stores"><div class="shell"><div class="section-head"><div><h2>{{ __('storefront.marketplace.shops') }}</h2><p class="muted">{{ __('storefront.marketplace.active_only') }}</p></div><span class="muted">{{ __('storefront.marketplace.shop_count',['count'=>$storefronts->total()]) }}</span></div>@if($storefronts->count())<div class="shop-grid">@foreach($storefronts as $storefront)<article class="card shop"><div class="cover" @if($storefront->cover_url) style="background-image:url('{{ $storefront->cover_url }}')" @endif></div><div class="shop-body"><h3>{{ $storefront->display_name }}</h3><div class="shop-city">{{ $storefront->city ?: __('storefront.common.pakistan') }}</div><p>{{ $storefront->tagline ?: __('storefront.marketplace.default_tagline') }}</p><div class="tags">@if($storefront->show_clothing && $storefront->business->clothing_enabled)<span class="pill">{{ __('storefront.common.clothing') }}</span>@endif @if($storefront->show_tailoring && $storefront->business->tailoring_enabled)<span class="pill">{{ __('storefront.common.tailoring') }}</span>@endif @if($storefront->offersDelivery())<span class="pill">{{ __('storefront.common.delivery') }}</span>@endif</div><a class="btn" href="{{ route('storefront.show',$storefront) }}">{{ __('storefront.marketplace.view_shop') }}</a></div></article>@endforeach</div>@if($storefronts->hasPages())<div style="margin-top:25px">{{ $storefronts->links() }}</div>@endif @else<div class="card empty"><h2>{{ __('storefront.marketplace.empty_title') }}</h2><p class="muted">{{ __('storefront.marketplace.empty_text') }}</p></div>@endif</div></section>

<section class="market-section" style="padding-top:0"><div class="shell"><div class="business-cta"><div><h2>{{ __('storefront.marketplace.business_cta_title') }}</h2><p class="muted">{{ __('storefront.marketplace.business_cta_text') }}</p></div><a class="btn" href="{{ route('storefront.business') }}">{{ __('storefront.marketplace.business_cta_button') }}</a></div></div></section>

<section class="market-section soft"><div class="shell"><div class="section-head"><div><h2>{{ __('storefront.marketplace.faq_title') }}</h2></div></div><div class="faq-grid">@foreach([['faq_one_q','faq_one_a'],['faq_two_q','faq_two_a'],['faq_three_q','faq_three_a']] as [$question,$answer])<details class="card faq"><summary>{{ __('storefront.marketplace.'.$question) }}</summary><p class="muted">{{ __('storefront.marketplace.'.$answer) }}</p></details>@endforeach</div></div></section>
</main>
<footer class="footer"><div class="shell">{{ __('storefront.marketplace.footer') }} · © {{ now()->year }}</div></footer>
@endsection
