@extends('storefront.public.layout')
@section('title', __('storefront.order.title',['reference'=>$order->reference]).' — '.$storefront->display_name)
@section('body')
<nav class="nav"><div class="shell"><a class="nav-brand" href="{{ route('storefront.show',$storefront) }}">{{ $storefront->display_name }}</a><div class="nav-actions">@include('storefront.public.partials.language-switch')<a class="nav-link" href="{{ route('storefront.clothing.index',$storefront) }}">{{ __('storefront.common.back_to_shop') }}</a></div></div></nav>
<header class="hero"><div class="shell"><div>{{ __('storefront.order.online_order') }}</div><h1 dir="ltr">{{ $order->reference }}</h1></div></header>
<main class="section"><div class="shell">@if(session('success'))<div class="success">{{ session('success') }}</div>@endif @if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
@if(!$authorized)<section class="card"><h2>{{ __('storefront.order.secure_title') }}</h2><p class="muted">{{ __('storefront.order.secure_text') }}</p><form method="POST" action="{{ route('storefront.orders.authenticate',[$storefront,$order->reference]) }}">@csrf<div class="form-group"><label for="order_phone">{{ __('storefront.common.phone') }}</label><input id="order_phone" name="phone" dir="ltr" class="control" required maxlength="50"></div><div class="form-group"><label for="order_pin">{{ __('storefront.cart.pin') }}</label><input id="order_pin" name="pin" dir="ltr" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" class="control" required></div><button class="btn">{{ __('storefront.order.view') }}</button></form></section>
@else
<section class="card"><div class="row"><strong>{{ __('storefront.order.status') }}</strong><span class="pill">{{ __('storefront.order.statuses.'.$order->status) }}</span></div><div class="row"><strong>{{ __('storefront.order.customer') }}</strong><span>{{ $order->customer->name }}</span></div><div class="row"><strong>{{ __('storefront.order.placed_at') }}</strong><span>{{ $order->placed_at->format('d-m-Y h:i A') }}</span></div><div class="row"><strong>{{ __('storefront.order.fulfillment') }}</strong><span>{{ __('storefront.order.methods.'.$order->fulfillment_method) }}</span></div><div class="row"><strong>{{ __('storefront.order.payment_choice') }}</strong><span>{{ \App\Models\StorefrontOrder::publicPaymentMethods()[$order->payment_method] ?? $order->payment_method }}</span></div>
@if($order->payment_method===\App\Models\StorefrontOrder::PAYMENT_EASYPAISA)<div class="row"><strong>{{ __('storefront.order.payment_reference') }}</strong><span dir="ltr">{{ $order->payment_reference }}</span></div><div class="notice">@if($order->payment_verification_status===\App\Models\StorefrontOrder::VERIFICATION_VERIFIED){{ __('storefront.order.payment_verified') }}@elseif($order->payment_verification_status===\App\Models\StorefrontOrder::VERIFICATION_REJECTED){{ __('storefront.order.payment_rejected') }}@else{{ __('storefront.order.payment_pending') }}@endif</div>@endif
@if($order->delivery_address)<div class="row"><strong>{{ __('storefront.order.delivery_address') }}</strong><span>{{ $order->delivery_address }}</span></div>@endif</section>
<section class="card" style="margin-top:18px"><h2>{{ __('storefront.order.items') }}</h2>@foreach($order->items as $item)<div class="row"><div><strong>{{ $item->item_name }}</strong><div class="muted">{{ $item->color }} · {{ number_format($item->quantity,2) }}m × {{ __('storefront.common.rs') }} {{ number_format($item->unit_price,2) }}</div></div><strong>{{ __('storefront.common.rs') }} {{ number_format($item->line_total,2) }}</strong></div>@endforeach<div class="row price"><span>{{ __('storefront.order.total') }}</span><span>{{ __('storefront.common.rs') }} {{ number_format($order->subtotal,2) }}</span></div></section>
<div class="notice">{{ __('storefront.order.balance_note') }}</div>@if($order->customer_note)<section class="card"><strong>{{ __('storefront.order.your_note') }}</strong><p>{{ $order->customer_note }}</p></section>@endif
@endif</div></main>
@endsection
