@extends('storefront.public.layout')
@section('title', $storefront->localizedName().' — '.__('storefront.common.marketplace'))
@section('meta_description', \App\Support\StorefrontSeo::description($storefront->localized('description') ?: $storefront->localized('tagline'), __('storefront.home.default_description')))
@section('canonical_url', route('storefront.show',$storefront))
@section('meta_image', $storefront->cover_url ?: $storefront->logo_url ?: '')
@section('meta_image_alt', $storefront->localizedName())
@section('robots', $preview ? 'noindex,nofollow' : 'index,follow')
@if(!$preview)
@push('structured_data')
<script type="application/ld+json">{!! \App\Support\StorefrontSeo::json(\App\Support\StorefrontSeo::graph(
    \App\Support\StorefrontSeo::localBusiness($storefront)
)) !!}</script>
@endpush
@endif
@push('styles')
@include('storefront.public.partials.shop-navigation-styles')
.owner-preview{position:sticky;z-index:20;top:0;color:#fff;background:#12365a;box-shadow:0 6px 20px rgba(10,32,57,.2)}
.owner-preview .shell{min-height:64px;display:flex;align-items:center;justify-content:space-between;gap:16px}
.preview-copy{display:flex;align-items:center;gap:11px}.preview-icon{display:grid;place-items:center;flex:0 0 38px;width:38px;height:38px;border-radius:10px;color:#12365a;background:#fff}
.preview-copy strong,.preview-copy small{display:block}.preview-copy strong{font-size:.82rem}.preview-copy small{color:rgba(255,255,255,.72);font-size:.64rem}
.preview-actions{display:flex;align-items:center;gap:8px}.preview-status{padding:5px 10px;border-radius:999px;color:#573f00;background:#ffd66b;font-size:.65rem;font-weight:800}
.preview-action{min-height:39px;display:inline-flex;align-items:center;gap:7px;padding:7px 12px;border:1px solid rgba(255,255,255,.35);border-radius:9px;color:#fff;text-decoration:none;font-size:.68rem;font-weight:800}
.preview-action.is-primary{border-color:#fff;color:#12365a;background:#fff}
.store-hero{position:relative;min-height:430px;display:flex;align-items:center;overflow:hidden;padding:0;background:linear-gradient(135deg,var(--primary),var(--accent));background-size:var(--hero-fit,cover);background-position:var(--hero-position,center);background-repeat:no-repeat}.store-hero:before{content:"";position:absolute;z-index:1;inset:0;background:linear-gradient(90deg,rgba(4,35,26,var(--hero-overlay,.7)),rgba(7,63,47,var(--hero-overlay,.7)))}.store-hero:after{content:"";position:absolute;z-index:1;top:50%;right:7%;width:280px;height:280px;border:1px solid rgba(255,255,255,.16);border-radius:50%;box-shadow:0 0 0 64px rgba(255,255,255,.045),0 0 0 128px rgba(255,255,255,.025);transform:translateY(-50%)}.store-hero:has(.hero-video):after,.store-hero[style*="background-image"]:after,.store-hero.is-split:after{display:none}.store-hero .shell{position:relative;z-index:2}.store-hero.height-compact{min-height:330px}.store-hero.height-tall{min-height:600px}.hero-video{position:absolute;z-index:0;inset:0;width:100%;height:100%;object-fit:var(--hero-fit,cover);object-position:var(--hero-position,center)}
.store-hero-content{max-width:940px;padding:34px 0}.store-hero h1{margin:10px 0 8px;font-size:clamp(2.15rem,5vw,4rem);line-height:1.12}.store-hero p{margin:0;max-width:720px;font-size:1rem;line-height:1.75}
html[lang="ur"] .store-hero h1{line-height:1.25!important}html[lang="ur"] .store-hero p{line-height:1.7!important}
.store-hero-content.animate-fade{animation:brandFade .65s ease both}.store-hero-content.animate-fade_up{animation:brandFadeUp .7s ease both}.store-hero-content.animate-slide{animation:brandSlide .7s ease both}@keyframes brandFade{from{opacity:0}to{opacity:1}}@keyframes brandFadeUp{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:none}}@keyframes brandSlide{from{opacity:0;transform:translateX(-34px)}to{opacity:1;transform:none}}
.store-hero.is-center{text-align:center}.store-hero.is-center .store-hero-content{margin-inline:auto}.store-hero.is-center .store-hero p{margin-inline:auto}.store-hero.is-center .badges,.store-hero.is-center .hero-actions{justify-content:center}
.store-hero.is-split{color:var(--ink);background:var(--shop-background)}.store-hero.is-split:before{display:none}.store-hero.is-split h1,.store-hero.is-split p{color:var(--ink)}.store-hero.is-split .shell{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,.85fr);align-items:center;gap:34px}.store-hero.is-split .hero-media{position:relative;min-height:340px;overflow:hidden;border-radius:var(--shop-radius);background:linear-gradient(135deg,var(--primary),var(--accent));background-position:var(--hero-position,center);background-size:var(--hero-fit,cover);background-repeat:no-repeat;box-shadow:0 20px 50px rgba(13,40,31,.16)}.store-hero.is-split .badge{color:var(--ink);border-color:var(--line);background:var(--shop-surface)}.store-hero.is-split .hero-btn{color:#fff;background:var(--primary)}.store-hero.is-split .hero-btn.is-outline{color:var(--primary);border-color:var(--primary);background:transparent}
.store-hero.is-minimal{min-height:330px;background:linear-gradient(120deg,var(--primary),var(--accent))}.store-hero.is-minimal .hero-media{display:none}
.hero-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:22px}.hero-btn{min-height:48px;display:inline-flex;align-items:center;gap:8px;padding:9px 18px;border-radius:10px;color:var(--primary-dark);background:#fff;text-decoration:none;font-weight:900}.hero-btn.is-outline{border:1px solid rgba(255,255,255,.55);color:#fff;background:rgba(255,255,255,.1)}
.store-hero.has-slider{display:block}.store-hero.has-slider:before,.store-hero.has-slider:after{display:none}.hero-slides{position:relative;min-height:inherit}.hero-slide{position:absolute;inset:0;display:flex;align-items:center;visibility:hidden;opacity:0;transition:opacity .45s ease}.hero-slide.is-current{visibility:visible;opacity:1}.hero-slide:before{content:"";position:absolute;z-index:1;inset:0;background:linear-gradient(90deg,rgba(4,35,26,var(--slide-overlay,.65)),rgba(7,63,47,var(--slide-overlay,.65)))}.hero-slide-media{position:absolute;z-index:0;inset:0;width:100%;height:100%;object-fit:var(--hero-fit,cover);object-position:var(--hero-position,center)}.hero-slide .shell{width:100%}.hero-slider-controls{position:absolute;z-index:4;right:max(20px,calc((100vw - 1180px)/2));bottom:22px;display:flex;align-items:center;gap:8px}.hero-slider-button,.hero-slider-dot{border:1px solid rgba(255,255,255,.6);color:#fff;background:rgba(0,0,0,.25);cursor:pointer}.hero-slider-button{width:38px;height:38px;border-radius:50%;font-size:1.2rem}.hero-slider-dot{width:10px;height:10px;padding:0;border-radius:50%}.hero-slider-dot.is-current{background:#fff}.hero-slide.is-center{text-align:center}.hero-slide.is-center .store-hero-content{margin-inline:auto}.hero-slide.is-center .store-hero p{margin-inline:auto}.hero-slide.is-center .badges,.hero-slide.is-center .hero-actions{justify-content:center}
.badges{display:flex;gap:8px;flex-wrap:wrap}.badge{background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.3);border-radius:999px;padding:5px 11px;font-size:.68rem}
.benefits{position:relative;z-index:2;display:grid;grid-template-columns:repeat(3,1fr);margin-top:-1px;border:1px solid var(--line);border-radius:0 0 14px 14px;background:#fff;box-shadow:0 8px 22px rgba(21,66,51,.06)}.benefit{display:flex;align-items:center;justify-content:center;gap:10px;padding:14px;border-left:1px solid var(--line);font-size:.72rem;font-weight:800}.benefit:last-child{border-left:0}.benefit i{color:var(--primary);font-size:1rem}
.section-heading{display:flex;align-items:end;justify-content:space-between;gap:15px;margin-bottom:17px}.section-heading h2{margin:0;color:var(--ink);font-size:1.35rem}.section-heading p{margin:3px 0 0}.section-link{color:var(--primary);font-size:.72rem;font-weight:900;text-decoration:none;white-space:nowrap}
.commerce-layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:18px;align-items:start}.category-sidebar{position:sticky;top:82px;padding:16px}.category-sidebar h3{margin:0 0 10px;font-size:.92rem}.category-group+.category-group{padding-top:14px;margin-top:14px;border-top:1px solid var(--line)}.category-group-title{display:block;margin-bottom:7px;color:var(--muted);font-size:.63rem;font-weight:800}.category-list{display:grid;gap:4px}.category-list a{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px;border-radius:8px;color:var(--ink);font-size:.68rem;text-decoration:none}.category-list a:hover{color:var(--primary);background:#eef6f2}.category-list i{color:var(--primary)}.brand-cloud{display:flex;flex-wrap:wrap;gap:6px}.brand-cloud a{padding:5px 9px;border:1px solid var(--line);border-radius:999px;color:var(--ink);font-size:.62rem;text-decoration:none}.brand-cloud a:hover{border-color:var(--primary);color:var(--primary)}
.product-grid{display:grid;grid-template-columns:repeat({{ in_array((int)$storefront->product_columns,[2,3,4],true) ? (int)$storefront->product_columns : 3 }},minmax(0,1fr));gap:16px}.home-product{overflow:hidden;padding:0;border-radius:var(--shop-radius)}.product-photo{position:relative;display:grid;place-items:center;overflow:hidden;background:linear-gradient(135deg,#e5f0eb,#f5f8f7);font-size:2.6rem;aspect-ratio:{{ match($storefront->product_image_ratio){'square'=>'1 / 1','landscape'=>'4 / 3','natural'=>'auto',default=>'4 / 5'} }}}.product-photo img{width:100%;height:100%;object-fit:cover;transition:transform .25s ease}.home-product:hover .product-photo img{transform:scale(1.04)}.product-featured{position:absolute;top:10px;right:10px;padding:4px 9px;border-radius:999px;color:#fff;background:var(--accent);font-size:.6rem;font-weight:900}.product-content{padding:14px}.product-content h3{overflow:hidden;margin:0;color:var(--ink);font-size:.9rem;text-overflow:ellipsis;white-space:nowrap}.product-meta{margin:3px 0;color:var(--muted);font-size:.63rem}.product-stock{display:flex;align-items:center;gap:5px;margin-top:6px;color:#247a59;font-size:.62rem;font-weight:800}.product-stock.is-empty{color:#a14444}.product-bottom{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:11px}.product-price{font-size:.78rem;font-weight:900}.product-view{display:grid;place-items:center;width:36px;height:36px;border-radius:var(--shop-radius);color:#fff;background:var(--primary);text-decoration:none}.products-empty{grid-column:1/-1;padding:30px;text-align:center}
.tailoring-strip{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.service-mini{padding:17px}.service-mini h3{margin:0 0 3px;font-size:.9rem}.service-mini p{margin:0}.service-price{display:block;margin-top:9px;color:var(--primary);font-weight:900}
.store-options{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.store-options .card{min-height:210px;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;padding:25px}.store-options h2{margin:0 0 5px;font-size:1.15rem}.store-options p{margin:0 0 15px}.store-option-icon{display:grid;place-items:center;width:44px;height:44px;margin-bottom:12px;border-radius:12px;color:var(--primary);background:#e7f4ef;font-size:1.05rem}
.about{background:var(--shop-surface)}.about-copy{padding:10px 0}.about-copy h2,.contact-card h2{margin-top:0;font-size:1.15rem}.contact-line{display:flex;align-items:flex-start;gap:9px;margin:10px 0}.contact-line i{width:18px;margin-top:9px;color:var(--primary);text-align:center}.contact-line p{margin:0}
@media(max-width:1000px){.product-grid{grid-template-columns:repeat({{ in_array((int)$storefront->product_columns_tablet,[1,2,3],true) ? (int)$storefront->product_columns_tablet : 2 }},minmax(0,1fr))}.commerce-layout{grid-template-columns:1fr}.category-sidebar{position:static;order:-1}}
@media(max-width:760px){.owner-preview .shell{align-items:flex-start;flex-direction:column;padding:10px 0}.preview-actions{width:100%;flex-wrap:wrap}.preview-action{flex:1}.store-hero{min-height:360px}.store-hero.height-compact{min-height:290px}.store-hero.height-tall{min-height:480px}.store-hero.has-slider,.store-hero.has-slider.height-compact{min-height:440px}.store-hero.has-slider.height-tall{min-height:520px}.store-hero-content{padding:20px 0}.hero-slide .store-hero-content{padding:36px 0 86px}.store-hero h1{font-size:clamp(2rem,10vw,3rem);line-height:1.18}.store-hero p{line-height:1.65}.store-hero:after{right:-155px;width:260px;height:260px}.store-hero.is-split .shell{grid-template-columns:1fr;gap:8px;padding-block:18px}.store-hero.is-split .hero-media{min-height:180px;order:-1}.hero-slider-controls{right:18px;bottom:20px}.store-options .card{min-height:0}.preview-status{order:3}.benefits{grid-template-columns:1fr}.benefit{justify-content:flex-start;border-left:0;border-bottom:1px solid var(--line)}.benefit:last-child{border-bottom:0}.section-heading{align-items:flex-start;flex-direction:column}}
@media(max-width:520px){.product-grid{grid-template-columns:repeat({{ in_array((int)$storefront->product_columns_mobile,[1,2],true) ? (int)$storefront->product_columns_mobile : 1 }},minmax(0,1fr))}}
@media(prefers-reduced-motion:reduce){.store-hero-content{animation:none!important}.hero-video{display:none}}
@endpush
@section('body')
@php
    $shopHomeUrl = $preview ? route('admin.storefront.preview') : route('storefront.show', $storefront);
    $clothingUrl = $preview && ! $storefront->is_published
        ? route('admin.storefront.clothing.index')
        : route('storefront.clothing.index', $storefront);
    $tailoringUrl = $preview && ! $storefront->is_published
        ? route('admin.storefront.tailoring.services')
        : route('storefront.tailoring.index', $storefront);
@endphp
@if($preview)
<aside class="owner-preview"><div class="shell"><div class="preview-copy"><span class="preview-icon">@include('storefront.public.partials.icon', ['name' => 'eye'])</span><div><strong>{{ __('storefront.home.preview_owner') }}</strong><small>{{ __('storefront.home.preview',['status'=>$storefront->is_published?__('storefront.home.published'):__('storefront.home.draft')]) }}</small></div></div><div class="preview-actions"><span class="preview-status">{{ $storefront->is_published ? __('storefront.home.published') : __('storefront.home.draft') }}</span><a class="preview-action is-primary" href="{{ route('admin.storefront.edit') }}">@include('storefront.public.partials.icon', ['name' => 'edit']){{ __('storefront.home.edit_shop') }}</a>@if($storefront->is_published)<a class="preview-action" target="_blank" rel="noopener" href="{{ route('storefront.show',$storefront) }}">@include('storefront.public.partials.icon', ['name' => 'external-link']){{ __('storefront.home.open_public_shop') }}</a>@endif</div></div></aside>
@endif
@include('storefront.public.partials.shop-navigation')
@php
    $heroLayout = in_array($storefront->hero_layout, ['overlay','split','minimal'], true) ? $storefront->hero_layout : 'overlay';
    $heroAlignment = $storefront->hero_alignment === 'center' ? 'center' : 'start';
    $overlay = max(20, min(90, (int)($storefront->hero_overlay_strength ?? 70))) / 100;
    $heroHeight = in_array($storefront->hero_height, ['compact','standard','tall'], true) ? $storefront->hero_height : 'standard';
    $heroAnimation = in_array($storefront->hero_text_animation, ['fade','fade_up','slide'], true) ? $storefront->hero_text_animation : null;
    $heroFit = $storefront->hero_media_fit === 'contain' ? 'contain' : 'cover';
    $heroPosition = in_array($storefront->hero_media_position, ['top','bottom'], true) ? $storefront->hero_media_position : 'center';
    $heroMediaType = $storefront->hero_media_type === 'video' && $storefront->hero_video_url
        ? 'video' : ($storefront->hero_media_type === 'image' && $storefront->cover_url ? 'image' : 'color');
    $heroVars = "--hero-overlay:{$overlay};--hero-fit:{$heroFit};--hero-position:{$heroPosition}";
    $heroBackground = $heroMediaType === 'image' && $heroLayout !== 'split'
        ? "background-image:url('{$storefront->cover_url}');" : '';
    $configuredSlides = $storefront->relationLoaded('heroSlides') ? $storefront->heroSlides : collect();
@endphp
@if($configuredSlides->isNotEmpty())
<header class="hero store-hero has-slider height-{{ $heroHeight }}" style="{{ $heroVars }}" data-hero-slider>
    <div class="hero-slides">
        @foreach($configuredSlides as $slide)
            @php
                $primaryUrl = $slide->buttonUrl('primary');
                $secondaryUrl = $slide->buttonUrl('secondary');
                $slideOverlay = max(20,min(90,(int)$slide->overlay_strength))/100;
            @endphp
            <article class="hero-slide {{ $loop->first ? 'is-current' : '' }} is-{{ $slide->alignment === 'center' ? 'center' : 'start' }}" style="--slide-overlay:{{ $slideOverlay }}" data-hero-slide aria-hidden="{{ $loop->first ? 'false' : 'true' }}">
                @if($slide->media_type === 'video' && $slide->video_url)
                    <video class="hero-slide-media" autoplay muted loop playsinline preload="metadata" @if($slide->video_poster_url) poster="{{ $slide->video_poster_url }}" @endif><source src="{{ $slide->video_url }}"></video>
                @elseif($slide->media_type === 'image' && $slide->image_url)
                    <picture><source media="(max-width:640px)" srcset="{{ $slide->mobile_image_url ?: $slide->image_url }}"><img class="hero-slide-media" src="{{ $slide->image_url }}" alt=""></picture>
                @endif
                <div class="shell"><div class="store-hero-content {{ $heroAnimation ? 'animate-'.$heroAnimation : '' }}"><div class="badges"><span class="badge">@include('storefront.public.partials.icon', ['name' => 'check-circle']){{ __('storefront.home.active_business') }}</span>@if($storefront->offersPickup())<span class="badge">@include('storefront.public.partials.icon', ['name' => 'bag']){{ __('storefront.common.pickup') }}</span>@endif @if($storefront->offersDelivery())<span class="badge">@include('storefront.public.partials.icon', ['name' => 'truck']){{ __('storefront.common.delivery') }}</span>@endif</div><h1>{{ $slide->localized('title') }}</h1>@if($slide->localized('text'))<p>{{ $slide->localized('text') }}</p>@endif<div class="hero-actions">@if($primaryUrl)<a class="hero-btn" href="{{ $primaryUrl }}">{{ $slide->localized('primary_label') }}</a>@endif @if($secondaryUrl)<a class="hero-btn is-outline" href="{{ $secondaryUrl }}">{{ $slide->localized('secondary_label') }}</a>@endif</div></div></div>
            </article>
        @endforeach
    </div>
    @if($configuredSlides->count() > 1)<div class="hero-slider-controls"><button class="hero-slider-button" type="button" data-hero-prev aria-label="Previous slide">‹</button>@foreach($configuredSlides as $slide)<button class="hero-slider-dot {{ $loop->first ? 'is-current' : '' }}" type="button" data-hero-dot="{{ $loop->index }}" aria-label="Slide {{ $loop->iteration }}"></button>@endforeach<button class="hero-slider-button" type="button" data-hero-next aria-label="Next slide">›</button></div>@endif
</header>
@else
<header class="hero store-hero is-{{ $heroLayout }} is-{{ $heroAlignment }} height-{{ $heroHeight }}" style="{{ $heroVars }};{{ $heroBackground }}">@if($heroMediaType === 'video' && $heroLayout !== 'split')<video class="hero-video" autoplay muted loop playsinline preload="metadata" @if($storefront->hero_video_poster_url) poster="{{ $storefront->hero_video_poster_url }}" @endif><source src="{{ $storefront->hero_video_url }}"></video>@endif<div class="shell"><div class="store-hero-content {{ $heroAnimation ? 'animate-'.$heroAnimation : '' }}"><div class="badges"><span class="badge">@include('storefront.public.partials.icon', ['name' => 'check-circle']){{ __('storefront.home.active_business') }}</span>@if($storefront->offersPickup())<span class="badge">@include('storefront.public.partials.icon', ['name' => 'bag']){{ __('storefront.common.pickup') }}</span>@endif @if($storefront->offersDelivery())<span class="badge">@include('storefront.public.partials.icon', ['name' => 'truck']){{ __('storefront.common.delivery') }}</span>@endif</div><h1>{{ $storefront->localized('hero_title') ?: $storefront->localizedName() }}</h1><p>{{ $storefront->localized('hero_text') ?: $storefront->localized('tagline') ?: __('storefront.home.default_tagline') }}</p><div class="hero-actions">@if($storefront->show_clothing)<a class="hero-btn" href="{{ $clothingUrl }}">@include('storefront.public.partials.icon', ['name' => 'bag']){{ __('storefront.home.shop_now') }}</a>@endif @if($storefront->show_tailoring)<a class="hero-btn is-outline" href="{{ $tailoringUrl }}">@include('storefront.public.partials.icon', ['name' => 'scissors']){{ __('storefront.home.view_tailoring') }}</a>@endif</div></div>@if($heroLayout === 'split')<div class="hero-media" @if($heroMediaType === 'image') style="background-image:url('{{ $storefront->cover_url }}')" @endif aria-hidden="true">@if($heroMediaType === 'video')<video class="hero-video" autoplay muted loop playsinline preload="metadata" @if($storefront->hero_video_poster_url) poster="{{ $storefront->hero_video_poster_url }}" @endif><source src="{{ $storefront->hero_video_url }}"></video>@endif</div>@endif</div></header>
@endif
<main>
@if($storefront->show_benefits ?? true)
<div class="shell benefits">
    <div class="benefit">@include('storefront.public.partials.icon', ['name' => 'truck'])<span>{{ __('storefront.home.delivery_benefit') }}</span></div>
    <div class="benefit">@include('storefront.public.partials.icon', ['name' => 'store'])<span>{{ __('storefront.home.pickup_benefit') }}</span></div>
    <div class="benefit">@include('storefront.public.partials.icon', ['name' => 'headset'])<span>{{ __('storefront.home.support_benefit') }}</span></div>
</div>
@endif

@if($storefront->show_clothing && ($storefront->show_featured_products ?? true))
<section class="section"><div class="shell">
    <div class="commerce-layout"><div><div class="section-heading"><div><h2>{{ __('storefront.home.featured_products') }}</h2><p class="muted">{{ __('storefront.home.featured_products_text') }}</p></div><a class="section-link" href="{{ $clothingUrl }}">{{ __('storefront.home.all_products') }} @include('storefront.public.partials.icon', ['name' => 'arrow-left'])</a></div>
    <div class="product-grid">
        @forelse($storefront->clothingListings as $listing)
            @php($image = $listing->cloth?->images?->first(fn ($item) => $item->image_url))
            @php($productUrl = $preview && ! $storefront->is_published ? route('admin.storefront.clothing.index') : route('storefront.clothing.show', [$storefront, $listing]))
            @php($availableStock = (float) ($listing->cloth?->colors?->sum('length') ?? 0))
            <article class="card home-product">
                <a class="product-photo" href="{{ $productUrl }}" aria-label="{{ $listing->localizedName() }}">@if($image)<img src="{{ $image->image_url }}" alt="{{ $listing->localizedName() }}">@else @include('storefront.public.partials.icon', ['name' => 'shirt', 'class' => 'is-xl']) @endif @if($listing->is_featured)<span class="product-featured">{{ __('storefront.clothing.featured') }}</span>@endif</a>
                <div class="product-content"><h3>{{ $listing->localizedName() }}</h3>@if(($storefront->show_product_brand ?? true) || ($storefront->show_product_category ?? true))<div class="product-meta">@if($storefront->show_product_brand ?? true){{ $listing->cloth?->brand?->name ?? __('storefront.clothing.no_brand') }}@endif @if(($storefront->show_product_brand ?? true) && ($storefront->show_product_category ?? true)) · @endif @if($storefront->show_product_category ?? true){{ $listing->cloth?->type?->localizedName() ?? __('storefront.clothing.fabric') }}@endif</div>@endif @if($storefront->show_product_stock ?? true)<div class="product-stock {{ $availableStock <= 0 ? 'is-empty' : '' }}">@include('storefront.public.partials.icon', ['name' => $availableStock > 0 ? 'check-circle' : 'box']){{ $availableStock > 0 ? __('storefront.clothing.available',['amount'=>number_format($availableStock,2)]) : __('storefront.clothing.out_of_stock') }}</div>@endif<div class="product-bottom"><span class="product-price">{!! \App\Support\PakistanCurrency::html($listing->cloth?->sale_price ?: $listing->cloth?->price) !!} <small class="muted">{{ __('storefront.clothing.per_metre') }}</small></span><a class="product-view" href="{{ $productUrl }}" title="{{ __('storefront.home.view_product') }}">@include('storefront.public.partials.icon', ['name' => 'bag'])</a></div></div>
            </article>
        @empty
            <div class="card products-empty"><span class="featured">@include('storefront.public.partials.icon', ['name' => 'box', 'class' => 'is-lg'])</span><h3>{{ __('storefront.clothing.empty_title') }}</h3><p class="muted">{{ __('storefront.clothing.empty_text') }}</p>@if($preview)<a class="btn" href="{{ route('admin.storefront.clothing.index') }}">{{ __('storefront.home.edit_shop') }}</a>@endif</div>
        @endforelse
    </div>
    </div><aside class="card category-sidebar"><h3>@include('storefront.public.partials.icon', ['name' => 'grid']){{ __('storefront.home.shop_categories') }}</h3>@if($clothTypes->isNotEmpty())<div class="category-group"><span class="category-group-title">{{ __('storefront.home.browse_by_type') }}</span><div class="category-list">@foreach($clothTypes as $type)<a href="{{ $clothingUrl }}?type={{ $type->id }}"><span>@include('storefront.public.partials.icon', ['name' => 'tag']){{ $type->localizedName() }}</span>@include('storefront.public.partials.icon', ['name' => 'chevron-left'])</a>@endforeach</div></div>@endif @if($clothBrands->isNotEmpty())<div class="category-group"><span class="category-group-title">{{ __('storefront.home.browse_by_brand') }}</span><div class="brand-cloud">@foreach($clothBrands as $brand)<a href="{{ $clothingUrl }}?q={{ urlencode($brand->name) }}">{{ $brand->name }}</a>@endforeach</div></div>@endif</aside></div>
</div></section>
@endif

@if($storefront->show_services ?? true)<section class="section" style="background:var(--shop-background)"><div class="shell"><div class="section-heading"><div><h2>{{ __('storefront.home.our_services') }}</h2></div></div><div class="store-options">@if($storefront->show_clothing)<article class="card"><span class="store-option-icon">@include('storefront.public.partials.icon', ['name' => 'shirt'])</span><h2>{{ __('storefront.common.clothing') }}</h2><p class="muted">{{ __('storefront.home.clothing_text') }}</p><a class="btn" href="{{ $clothingUrl }}">@include('storefront.public.partials.icon', ['name' => 'bag']){{ __('storefront.home.view_clothing') }}</a></article>@endif @if($storefront->show_tailoring)<article class="card"><span class="store-option-icon">@include('storefront.public.partials.icon', ['name' => 'scissors'])</span><h2>{{ __('storefront.common.tailoring') }}</h2><p class="muted">{{ __('storefront.home.tailoring_text') }}</p><a class="btn" href="{{ $tailoringUrl }}">@include('storefront.public.partials.icon', ['name' => 'arrow-left']){{ __('storefront.home.view_tailoring') }}</a></article>@endif</div></div></section>@endif

@if($storefront->show_tailoring && $storefront->tailoringServices->isNotEmpty())
<section class="section"><div class="shell"><div class="section-heading"><div><h2>{{ __('storefront.common.tailoring') }}</h2><p class="muted">{{ __('storefront.home.tailoring_text') }}</p></div><a class="section-link" href="{{ $tailoringUrl }}">{{ __('storefront.home.view_tailoring') }}</a></div><div class="tailoring-strip">@foreach($storefront->tailoringServices as $service)<article class="card service-mini"><h3>{{ $service->localizedName() }}</h3><p class="muted">{{ \Illuminate\Support\Str::limit($service->localizedDescription(), 85) }}</p>@if($service->price_from !== null)<span class="service-price">{!! \App\Support\PakistanCurrency::html($service->price_from) !!}</span>@endif</article>@endforeach</div></div></section>
@endif
@if($storefront->show_about ?? true)<section class="section about" id="shop-contact"><div class="shell two-col"><div class="about-copy"><h2>{{ __('storefront.home.about') }}</h2><p>{{ $storefront->localized('description') ?: $storefront->localized('tagline') ?: __('storefront.home.default_description') }}</p></div><aside class="card contact-card"><h2>{{ __('storefront.home.contact') }}</h2>@if($storefront->public_phone)<div class="contact-line">@include('storefront.public.partials.icon', ['name' => 'phone'])<p><strong>{{ __('storefront.common.phone') }}:</strong> <a dir="ltr" href="tel:{{ preg_replace('/[^0-9+]/','',$storefront->public_phone) }}">{{ $storefront->public_phone }}</a></p></div>@endif @if($storefront->whatsapp_number)<div class="contact-line">@include('storefront.public.partials.icon', ['name' => 'phone'])<p><strong>WhatsApp:</strong> <a dir="ltr" target="_blank" rel="noopener noreferrer" href="https://wa.me/{{ preg_replace('/[^0-9]/','',$storefront->whatsapp_number) }}">{{ $storefront->whatsapp_number }}</a></p></div>@endif @if($storefront->public_email)<div class="contact-line"><p><strong>{{ __('storefront.common.email') }}:</strong> <a dir="ltr" href="mailto:{{ $storefront->public_email }}">{{ $storefront->public_email }}</a></p></div>@endif @if($storefront->localized('address'))<div class="contact-line">@include('storefront.public.partials.icon', ['name' => 'map-pin'])<p><strong>{{ __('storefront.common.address') }}:</strong> {{ $storefront->localized('address') }}</p></div>@endif @if($storefront->localized('city'))<div class="contact-line"><p><strong>{{ __('storefront.common.city') }}:</strong> {{ $storefront->localized('city') }}</p></div>@endif</aside></div></section>@endif
</main>@include('storefront.public.partials.shop-footer')
@if($configuredSlides->count() > 1)
@push('scripts')
<script>(()=>{const root=document.querySelector('[data-hero-slider]');if(!root)return;const slides=[...root.querySelectorAll('[data-hero-slide]')],dots=[...root.querySelectorAll('[data-hero-dot]')];let current=0,timer;const show=index=>{current=(index+slides.length)%slides.length;slides.forEach((slide,i)=>{const active=i===current;slide.classList.toggle('is-current',active);slide.setAttribute('aria-hidden',active?'false':'true');slide.querySelectorAll('video').forEach(video=>active?video.play().catch(()=>{}):video.pause())});dots.forEach((dot,i)=>dot.classList.toggle('is-current',i===current))};const start=()=>{if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)timer=setInterval(()=>show(current+1),6500)};const restart=()=>{clearInterval(timer);start()};root.querySelector('[data-hero-prev]')?.addEventListener('click',()=>{show(current-1);restart()});root.querySelector('[data-hero-next]')?.addEventListener('click',()=>{show(current+1);restart()});dots.forEach(dot=>dot.addEventListener('click',()=>{show(Number(dot.dataset.heroDot));restart()}));root.addEventListener('mouseenter',()=>clearInterval(timer));root.addEventListener('mouseleave',start);show(0);start()})()</script>
@endpush
@endif
@endsection
