@extends('storefront.public.layout')
@section('title', $storefront->display_name.' — '.__('storefront.common.marketplace'))
@push('styles')
.preview{background:#f9c74f;color:#3d3100;text-align:center;padding:9px;font-weight:800}.logo{width:44px;height:44px;border-radius:13px;object-fit:cover;background:#dcece5}.store-hero{min-height:410px;display:flex;align-items:end;background:linear-gradient(90deg,rgba(5,40,29,.93),rgba(5,40,29,.48)),linear-gradient(135deg,#137253,#69b99b);background-size:cover;background-position:center}.badges{display:flex;gap:8px;flex-wrap:wrap}.badge{background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.28);border-radius:999px;padding:7px 12px}.about{background:#e9f4ef}
@endpush
@section('body')
@if($preview)<div class="preview">{{ __('storefront.home.preview',['status'=>$storefront->is_published?__('storefront.home.published'):__('storefront.home.draft')]) }}</div>@endif
<nav class="nav"><div class="shell"><a class="nav-brand" href="{{ route('storefront.show',$storefront) }}">@if($storefront->logo_url)<img class="logo" src="{{ $storefront->logo_url }}" alt="{{ __('storefront.home.logo_alt',['shop'=>$storefront->display_name]) }}">@endif {{ $storefront->display_name }}</a><div class="nav-actions">@include('storefront.public.partials.language-switch')<a class="nav-link" href="{{ route('storefront.index') }}">{{ __('storefront.common.all_shops') }}</a></div></div></nav>
<header class="hero store-hero" @if($storefront->cover_url) style="background-image:linear-gradient(90deg,rgba(5,40,29,.93),rgba(5,40,29,.48)),url('{{ $storefront->cover_url }}')" @endif><div class="shell"><div class="badges"><span class="badge">{{ __('storefront.home.active_business') }}</span>@if($storefront->pickup_enabled)<span class="badge">{{ __('storefront.common.pickup') }}</span>@endif @if($storefront->delivery_enabled)<span class="badge">{{ __('storefront.common.delivery') }}</span>@endif</div><h1>{{ $storefront->display_name }}</h1><p>{{ $storefront->tagline ?: __('storefront.home.default_tagline') }}</p></div></header>
<main>
<section class="section"><div class="shell grid">@if($storefront->show_clothing)<article class="card"><h2>{{ __('storefront.common.clothing') }}</h2><p class="muted">{{ __('storefront.home.clothing_text') }}</p><a class="btn" href="{{ route('storefront.clothing.index',$storefront) }}">{{ __('storefront.home.view_clothing') }}</a></article>@endif @if($storefront->show_tailoring)<article class="card"><h2>{{ __('storefront.common.tailoring') }}</h2><p class="muted">{{ __('storefront.home.tailoring_text') }}</p><a class="btn" href="{{ route('storefront.tailoring.index',$storefront) }}">{{ __('storefront.home.view_tailoring') }}</a></article>@endif</div></section>
<section class="section about"><div class="shell two-col"><div><h2>{{ __('storefront.home.about') }}</h2><p>{{ $storefront->description ?: $storefront->tagline ?: __('storefront.home.default_description') }}</p></div><aside class="card"><h2>{{ __('storefront.home.contact') }}</h2>@if($storefront->public_phone)<p><strong>{{ __('storefront.common.phone') }}:</strong> <a dir="ltr" href="tel:{{ preg_replace('/[^0-9+]/','',$storefront->public_phone) }}">{{ $storefront->public_phone }}</a></p>@endif @if($storefront->public_email)<p><strong>{{ __('storefront.common.email') }}:</strong> <a dir="ltr" href="mailto:{{ $storefront->public_email }}">{{ $storefront->public_email }}</a></p>@endif @if($storefront->address)<p><strong>{{ __('storefront.common.address') }}:</strong> {{ $storefront->address }}</p>@endif @if($storefront->city)<p><strong>{{ __('storefront.common.city') }}:</strong> {{ $storefront->city }}</p>@endif</aside></div></section>
</main><footer class="footer"><div class="shell">{{ $storefront->display_name }} · {{ __('storefront.common.marketplace') }}</div></footer>
@endsection
