@extends('storefront.public.layout')
@section('title', $storefront->display_name.' — '.__('storefront.common.marketplace'))
@section('meta_description', \App\Support\StorefrontSeo::description($storefront->description ?: $storefront->tagline, __('storefront.home.default_description')))
@section('canonical_url', route('storefront.show',$storefront))
@section('meta_image', $storefront->cover_url ?: $storefront->logo_url ?: '')
@section('meta_image_alt', $storefront->display_name)
@section('robots', $preview ? 'noindex,nofollow' : 'index,follow')
@if(!$preview)
@push('structured_data')
<script type="application/ld+json">{!! \App\Support\StorefrontSeo::json(\App\Support\StorefrontSeo::graph(
    \App\Support\StorefrontSeo::localBusiness($storefront)
)) !!}</script>
@endpush
@endif
@push('styles')
.owner-preview{position:sticky;z-index:20;top:0;color:#fff;background:#12365a;box-shadow:0 6px 20px rgba(10,32,57,.2)}
.owner-preview .shell{min-height:64px;display:flex;align-items:center;justify-content:space-between;gap:16px}
.preview-copy{display:flex;align-items:center;gap:11px}.preview-icon{display:grid;place-items:center;flex:0 0 38px;width:38px;height:38px;border-radius:10px;color:#12365a;background:#fff}
.preview-copy strong,.preview-copy small{display:block}.preview-copy strong{font-size:.82rem}.preview-copy small{color:rgba(255,255,255,.72);font-size:.64rem}
.preview-actions{display:flex;align-items:center;gap:8px}.preview-status{padding:5px 10px;border-radius:999px;color:#573f00;background:#ffd66b;font-size:.65rem;font-weight:800}
.preview-action{min-height:39px;display:inline-flex;align-items:center;gap:7px;padding:7px 12px;border:1px solid rgba(255,255,255,.35);border-radius:9px;color:#fff;text-decoration:none;font-size:.68rem;font-weight:800}
.preview-action.is-primary{border-color:#fff;color:#12365a;background:#fff}
.logo{width:46px;height:46px;margin-left:8px;border-radius:13px;object-fit:cover;background:#dcece5}
.shop-nav .shell{min-height:82px}.shop-nav .nav-brand{font-size:1rem}.shop-search{display:flex;flex:1;max-width:500px;margin:0 18px}.shop-search input{width:100%;min-height:44px;padding:8px 14px;border:1px solid #cbd9d3;border-radius:0 10px 10px 0;background:#f8fbfa;font:inherit}.shop-search button{min-width:48px;border:0;border-radius:10px 0 0 10px;color:#fff;background:var(--primary);cursor:pointer}.cart-link{position:relative}.cart-link i{font-size:.9rem}
.category-nav{position:relative;z-index:4;border-bottom:1px solid var(--line);background:#fff}.category-nav .shell{min-height:52px;display:flex;align-items:center;gap:6px;overflow:visible}.category-link,.category-drop summary{min-height:39px;display:inline-flex;align-items:center;gap:7px;padding:6px 12px;border-radius:8px;color:var(--ink);text-decoration:none;font-size:.7rem;font-weight:800;cursor:pointer;list-style:none;white-space:nowrap}.category-link:hover,.category-link.is-active,.category-drop[open] summary{color:var(--primary);background:#eaf3ef}.category-drop{position:relative}.category-drop summary::-webkit-details-marker{display:none}.category-menu{position:absolute;z-index:8;top:44px;right:0;width:260px;padding:10px;border:1px solid var(--line);border-radius:12px;background:#fff;box-shadow:0 14px 34px rgba(19,55,43,.16)}.category-menu a{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px 10px;border-radius:7px;color:var(--ink);font-size:.68rem;text-decoration:none}.category-menu a:hover{color:var(--primary);background:#f0f6f3}.category-menu small{color:var(--muted)}
.store-hero{position:relative;min-height:430px;display:flex;align-items:center;background:linear-gradient(90deg,rgba(4,35,26,.94),rgba(7,63,47,.62)),linear-gradient(135deg,#0b4937,#4ca887);background-size:cover;background-position:center}
.store-hero-content{max-width:760px;padding:35px 0}.store-hero h1{margin:10px 0 2px;font-size:clamp(2.15rem,5vw,4rem);line-height:1.55}.store-hero p{margin:0;max-width:680px;font-size:1rem;line-height:2.2}
.hero-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:22px}.hero-btn{min-height:48px;display:inline-flex;align-items:center;gap:8px;padding:9px 18px;border-radius:10px;color:var(--primary-dark);background:#fff;text-decoration:none;font-weight:900}.hero-btn.is-outline{border:1px solid rgba(255,255,255,.55);color:#fff;background:rgba(255,255,255,.1)}
.badges{display:flex;gap:8px;flex-wrap:wrap}.badge{background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.3);border-radius:999px;padding:5px 11px;font-size:.68rem}
.benefits{position:relative;z-index:2;display:grid;grid-template-columns:repeat(3,1fr);margin-top:-1px;border:1px solid var(--line);border-radius:0 0 14px 14px;background:#fff;box-shadow:0 8px 22px rgba(21,66,51,.06)}.benefit{display:flex;align-items:center;justify-content:center;gap:10px;padding:14px;border-left:1px solid var(--line);font-size:.72rem;font-weight:800}.benefit:last-child{border-left:0}.benefit i{color:var(--primary);font-size:1rem}
.section-heading{display:flex;align-items:end;justify-content:space-between;gap:15px;margin-bottom:17px}.section-heading h2{margin:0;color:var(--ink);font-size:1.35rem}.section-heading p{margin:3px 0 0}.section-link{color:var(--primary);font-size:.72rem;font-weight:900;text-decoration:none;white-space:nowrap}
.commerce-layout{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:18px;align-items:start}.category-sidebar{position:sticky;top:82px;padding:16px}.category-sidebar h3{margin:0 0 10px;font-size:.92rem}.category-group+.category-group{padding-top:14px;margin-top:14px;border-top:1px solid var(--line)}.category-group-title{display:block;margin-bottom:7px;color:var(--muted);font-size:.63rem;font-weight:800}.category-list{display:grid;gap:4px}.category-list a{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px;border-radius:8px;color:var(--ink);font-size:.68rem;text-decoration:none}.category-list a:hover{color:var(--primary);background:#eef6f2}.category-list i{color:var(--primary)}.brand-cloud{display:flex;flex-wrap:wrap;gap:6px}.brand-cloud a{padding:5px 9px;border:1px solid var(--line);border-radius:999px;color:var(--ink);font-size:.62rem;text-decoration:none}.brand-cloud a:hover{border-color:var(--primary);color:var(--primary)}
.product-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.home-product{overflow:hidden;padding:0;border-radius:14px}.product-photo{position:relative;height:210px;display:grid;place-items:center;overflow:hidden;background:linear-gradient(135deg,#e5f0eb,#f5f8f7);font-size:2.6rem}.product-photo img{width:100%;height:100%;object-fit:cover;transition:transform .25s ease}.home-product:hover .product-photo img{transform:scale(1.04)}.product-featured{position:absolute;top:10px;right:10px;padding:4px 9px;border-radius:999px;color:#fff;background:#d88314;font-size:.6rem;font-weight:900}.product-content{padding:14px}.product-content h3{overflow:hidden;margin:0;color:var(--ink);font-size:.9rem;text-overflow:ellipsis;white-space:nowrap}.product-meta{margin:3px 0;color:var(--muted);font-size:.63rem}.product-stock{display:flex;align-items:center;gap:5px;margin-top:6px;color:#247a59;font-size:.62rem;font-weight:800}.product-stock.is-empty{color:#a14444}.product-bottom{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:11px}.product-price{font-size:.78rem;font-weight:900}.product-view{display:grid;place-items:center;width:36px;height:36px;border-radius:9px;color:#fff;background:var(--primary);text-decoration:none}.products-empty{grid-column:1/-1;padding:30px;text-align:center}
.tailoring-strip{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.service-mini{padding:17px}.service-mini h3{margin:0 0 3px;font-size:.9rem}.service-mini p{margin:0}.service-price{display:block;margin-top:9px;color:var(--primary);font-weight:900}
.store-options{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.store-options .card{min-height:210px;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;padding:25px}.store-options h2{margin:0 0 5px;font-size:1.15rem}.store-options p{margin:0 0 15px}.store-option-icon{display:grid;place-items:center;width:44px;height:44px;margin-bottom:12px;border-radius:12px;color:var(--primary);background:#e7f4ef;font-size:1.05rem}
.about{background:#e9f4ef}.about-copy{padding:10px 0}.about-copy h2,.contact-card h2{margin-top:0;font-size:1.15rem}.contact-line{display:flex;align-items:flex-start;gap:9px;margin:10px 0}.contact-line i{width:18px;margin-top:9px;color:var(--primary);text-align:center}.contact-line p{margin:0}
@media(max-width:1000px){.product-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.shop-search{order:3;flex-basis:100%;max-width:none;margin:0 0 10px}.commerce-layout{grid-template-columns:1fr}.category-sidebar{position:static;order:-1}.category-nav .shell{overflow-x:auto}.category-drop{position:static}.category-menu{right:14px;left:14px;width:auto}}
@media(max-width:760px){.owner-preview .shell{align-items:flex-start;flex-direction:column;padding:10px 0}.preview-actions{width:100%;flex-wrap:wrap}.preview-action{flex:1}.store-hero{min-height:360px}.store-hero-content{padding:25px 0}.store-options .card{min-height:0}.preview-status{order:3}.benefits{grid-template-columns:1fr}.benefit{justify-content:flex-start;border-left:0;border-bottom:1px solid var(--line)}.benefit:last-child{border-bottom:0}.section-heading{align-items:flex-start;flex-direction:column}}
@media(max-width:520px){.product-grid{grid-template-columns:1fr}.shop-nav .nav-actions{width:100%;justify-content:space-between}.product-photo{height:245px}}
@endpush
@section('body')
@php
    $shopHomeUrl = $preview ? route('admin.storefront.preview') : route('storefront.show', $storefront);
    $clothingUrl = $preview && ! $storefront->is_published
        ? route('admin.storefront.clothing.index')
        : route('storefront.clothing.index', $storefront);
    $tailoringUrl = $preview && ! $storefront->is_published
        ? route('admin.storefront.tailoring.services')
        : route('storefront.tailoring.index', $storefront);
@endphp
@if($preview)
<aside class="owner-preview"><div class="shell"><div class="preview-copy"><span class="preview-icon"><i class="fas fa-eye"></i></span><div><strong>{{ __('storefront.home.preview_owner') }}</strong><small>{{ __('storefront.home.preview',['status'=>$storefront->is_published?__('storefront.home.published'):__('storefront.home.draft')]) }}</small></div></div><div class="preview-actions"><span class="preview-status">{{ $storefront->is_published ? __('storefront.home.published') : __('storefront.home.draft') }}</span><a class="preview-action is-primary" href="{{ route('admin.storefront.edit') }}"><i class="fas fa-edit"></i>{{ __('storefront.home.edit_shop') }}</a>@if($storefront->is_published)<a class="preview-action" target="_blank" rel="noopener" href="{{ route('storefront.show',$storefront) }}"><i class="fas fa-external-link-alt"></i>{{ __('storefront.home.open_public_shop') }}</a>@endif</div></div></aside>
@endif
<nav class="nav shop-nav"><div class="shell">
    <a class="nav-brand" href="{{ $shopHomeUrl }}">@if($storefront->logo_url)<img class="logo" src="{{ $storefront->logo_url }}" alt="{{ __('storefront.home.logo_alt',['shop'=>$storefront->display_name]) }}">@else<span class="logo" style="display:grid;place-items:center"><i class="fas fa-store"></i></span>@endif {{ $storefront->display_name }}</a>
    @if($storefront->show_clothing)<form class="shop-search" action="{{ $clothingUrl }}" method="GET"><input name="q" aria-label="{{ __('storefront.home.search_products') }}" placeholder="{{ __('storefront.home.search_placeholder') }}"><button type="submit" aria-label="{{ __('storefront.home.search_products') }}"><i class="fas fa-search"></i></button></form>@endif
    <div class="nav-actions">@include('storefront.public.partials.language-switch')
        @if(!$preview && $storefront->show_clothing && $storefront->clothingOrderingEnabled())<a class="nav-link cart-link" href="{{ route('storefront.cart.show',$storefront) }}"><i class="fas fa-shopping-cart ml-2"></i>{{ __('storefront.clothing.cart') }}</a>@endif
        <a class="nav-link" href="{{ route('storefront.index') }}"><i class="fas fa-th-large ml-2"></i>{{ __('storefront.common.all_shops') }}</a>
    </div>
</div></nav>
<nav class="category-nav" aria-label="{{ __('storefront.home.shop_categories') }}"><div class="shell">
    <a class="category-link is-active" href="{{ $shopHomeUrl }}"><i class="fas fa-home"></i>{{ __('storefront.home.nav_home') }}</a>
    @if($storefront->show_clothing)<a class="category-link" href="{{ $clothingUrl }}"><i class="fas fa-shopping-bag"></i>{{ __('storefront.home.all_products') }}</a>@endif
    @if($clothTypes->isNotEmpty())<details class="category-drop"><summary><i class="fas fa-th-large"></i>{{ __('storefront.home.nav_categories') }} <i class="fas fa-chevron-down"></i></summary><div class="category-menu">@foreach($clothTypes as $type)<a href="{{ $clothingUrl }}?type={{ $type->id }}"><span><i class="fas fa-tag ml-2"></i>{{ $type->name }}</span><i class="fas fa-arrow-left"></i></a>@endforeach</div></details>@endif
    @if($clothBrands->isNotEmpty())<details class="category-drop"><summary><i class="fas fa-copyright"></i>{{ __('storefront.home.nav_brands') }} <i class="fas fa-chevron-down"></i></summary><div class="category-menu">@foreach($clothBrands as $brand)<a href="{{ $clothingUrl }}?q={{ urlencode($brand->name) }}"><span><i class="fas fa-certificate ml-2"></i>{{ $brand->name }}</span><i class="fas fa-arrow-left"></i></a>@endforeach</div></details>@endif
    @if($storefront->show_tailoring)<a class="category-link" href="{{ $tailoringUrl }}"><i class="fas fa-cut"></i>{{ __('storefront.common.tailoring') }}</a>@endif
    <a class="category-link" href="#shop-contact"><i class="fas fa-phone-alt"></i>{{ __('storefront.home.contact') }}</a>
</div></nav>
<header class="hero store-hero" @if($storefront->cover_url) style="background-image:linear-gradient(90deg,rgba(4,35,26,.94),rgba(7,63,47,.62)),url('{{ $storefront->cover_url }}')" @endif><div class="shell"><div class="store-hero-content"><div class="badges"><span class="badge"><i class="fas fa-check-circle ml-1"></i>{{ __('storefront.home.active_business') }}</span>@if($storefront->offersPickup())<span class="badge"><i class="fas fa-shopping-bag ml-1"></i>{{ __('storefront.common.pickup') }}</span>@endif @if($storefront->offersDelivery())<span class="badge"><i class="fas fa-truck ml-1"></i>{{ __('storefront.common.delivery') }}</span>@endif</div><h1>{{ $storefront->display_name }}</h1><p>{{ $storefront->tagline ?: __('storefront.home.default_tagline') }}</p><div class="hero-actions">@if($storefront->show_clothing)<a class="hero-btn" href="{{ $clothingUrl }}"><i class="fas fa-shopping-bag"></i>{{ __('storefront.home.shop_now') }}</a>@endif @if($storefront->show_tailoring)<a class="hero-btn is-outline" href="{{ $tailoringUrl }}"><i class="fas fa-cut"></i>{{ __('storefront.home.view_tailoring') }}</a>@endif</div></div></div></header>
<main>
<div class="shell benefits">
    <div class="benefit"><i class="fas fa-truck"></i><span>{{ __('storefront.home.delivery_benefit') }}</span></div>
    <div class="benefit"><i class="fas fa-store-alt"></i><span>{{ __('storefront.home.pickup_benefit') }}</span></div>
    <div class="benefit"><i class="fas fa-headset"></i><span>{{ __('storefront.home.support_benefit') }}</span></div>
</div>

@if($storefront->show_clothing)
<section class="section"><div class="shell">
    <div class="commerce-layout"><div><div class="section-heading"><div><h2>{{ __('storefront.home.featured_products') }}</h2><p class="muted">{{ __('storefront.home.featured_products_text') }}</p></div><a class="section-link" href="{{ $clothingUrl }}">{{ __('storefront.home.all_products') }} <i class="fas fa-arrow-left"></i></a></div>
    <div class="product-grid">
        @forelse($storefront->clothingListings as $listing)
            @php($image = $listing->cloth?->images?->first(fn ($item) => $item->image_url))
            @php($productUrl = $preview && ! $storefront->is_published ? route('admin.storefront.clothing.index') : route('storefront.clothing.show', [$storefront, $listing]))
            @php($availableStock = (float) ($listing->cloth?->colors?->sum('length') ?? 0))
            <article class="card home-product">
                <a class="product-photo" href="{{ $productUrl }}" aria-label="{{ $listing->display_name }}">@if($image)<img src="{{ $image->image_url }}" alt="{{ $listing->display_name }}">@else<span>🧵</span>@endif @if($listing->is_featured)<span class="product-featured">{{ __('storefront.clothing.featured') }}</span>@endif</a>
                <div class="product-content"><h3>{{ $listing->display_name }}</h3><div class="product-meta">{{ $listing->cloth?->brand?->name ?? __('storefront.clothing.no_brand') }} · {{ $listing->cloth?->type?->name ?? __('storefront.clothing.fabric') }}</div><div class="product-stock {{ $availableStock <= 0 ? 'is-empty' : '' }}"><i class="fas {{ $availableStock > 0 ? 'fa-check-circle' : 'fa-times-circle' }}"></i>{{ $availableStock > 0 ? __('storefront.clothing.available',['amount'=>number_format($availableStock,2)]) : __('storefront.clothing.out_of_stock') }}</div><div class="product-bottom"><span class="product-price">{!! \App\Support\PakistanCurrency::html($listing->cloth?->sale_price ?: $listing->cloth?->price) !!} <small class="muted">{{ __('storefront.clothing.per_metre') }}</small></span><a class="product-view" href="{{ $productUrl }}" title="{{ __('storefront.home.view_product') }}"><i class="fas fa-shopping-bag"></i></a></div></div>
            </article>
        @empty
            <div class="card products-empty"><i class="fas fa-box-open featured" style="font-size:1.6rem"></i><h3>{{ __('storefront.clothing.empty_title') }}</h3><p class="muted">{{ __('storefront.clothing.empty_text') }}</p>@if($preview)<a class="btn" href="{{ route('admin.storefront.clothing.index') }}">{{ __('storefront.home.edit_shop') }}</a>@endif</div>
        @endforelse
    </div>
    </div><aside class="card category-sidebar"><h3><i class="fas fa-th-large ml-2 featured"></i>{{ __('storefront.home.shop_categories') }}</h3>@if($clothTypes->isNotEmpty())<div class="category-group"><span class="category-group-title">{{ __('storefront.home.browse_by_type') }}</span><div class="category-list">@foreach($clothTypes as $type)<a href="{{ $clothingUrl }}?type={{ $type->id }}"><span><i class="fas fa-tag ml-2"></i>{{ $type->name }}</span><i class="fas fa-chevron-left"></i></a>@endforeach</div></div>@endif @if($clothBrands->isNotEmpty())<div class="category-group"><span class="category-group-title">{{ __('storefront.home.browse_by_brand') }}</span><div class="brand-cloud">@foreach($clothBrands as $brand)<a href="{{ $clothingUrl }}?q={{ urlencode($brand->name) }}">{{ $brand->name }}</a>@endforeach</div></div>@endif</aside></div>
</div></section>
@endif

<section class="section" style="background:#eef5f2"><div class="shell"><div class="section-heading"><div><h2>{{ __('storefront.home.our_services') }}</h2></div></div><div class="store-options">@if($storefront->show_clothing)<article class="card"><span class="store-option-icon"><i class="fas fa-tshirt"></i></span><h2>{{ __('storefront.common.clothing') }}</h2><p class="muted">{{ __('storefront.home.clothing_text') }}</p><a class="btn" href="{{ $clothingUrl }}"><i class="fas fa-shopping-bag ml-2"></i>{{ __('storefront.home.view_clothing') }}</a></article>@endif @if($storefront->show_tailoring)<article class="card"><span class="store-option-icon"><i class="fas fa-cut"></i></span><h2>{{ __('storefront.common.tailoring') }}</h2><p class="muted">{{ __('storefront.home.tailoring_text') }}</p><a class="btn" href="{{ $tailoringUrl }}"><i class="fas fa-arrow-left ml-2"></i>{{ __('storefront.home.view_tailoring') }}</a></article>@endif</div></div></section>

@if($storefront->show_tailoring && $storefront->tailoringServices->isNotEmpty())
<section class="section"><div class="shell"><div class="section-heading"><div><h2>{{ __('storefront.common.tailoring') }}</h2><p class="muted">{{ __('storefront.home.tailoring_text') }}</p></div><a class="section-link" href="{{ $tailoringUrl }}">{{ __('storefront.home.view_tailoring') }} <i class="fas fa-arrow-left"></i></a></div><div class="tailoring-strip">@foreach($storefront->tailoringServices as $service)<article class="card service-mini"><h3>{{ $service->name }}</h3><p class="muted">{{ \Illuminate\Support\Str::limit($service->description, 85) }}</p>@if($service->price_from !== null)<span class="service-price">{!! \App\Support\PakistanCurrency::html($service->price_from) !!}</span>@endif</article>@endforeach</div></div></section>
@endif
<section class="section about" id="shop-contact"><div class="shell two-col"><div class="about-copy"><h2>{{ __('storefront.home.about') }}</h2><p>{{ $storefront->description ?: $storefront->tagline ?: __('storefront.home.default_description') }}</p></div><aside class="card contact-card"><h2>{{ __('storefront.home.contact') }}</h2>@if($storefront->public_phone)<div class="contact-line"><i class="fas fa-phone-alt"></i><p><strong>{{ __('storefront.common.phone') }}:</strong> <a dir="ltr" href="tel:{{ preg_replace('/[^0-9+]/','',$storefront->public_phone) }}">{{ $storefront->public_phone }}</a></p></div>@endif @if($storefront->public_email)<div class="contact-line"><i class="fas fa-envelope"></i><p><strong>{{ __('storefront.common.email') }}:</strong> <a dir="ltr" href="mailto:{{ $storefront->public_email }}">{{ $storefront->public_email }}</a></p></div>@endif @if($storefront->address)<div class="contact-line"><i class="fas fa-map-marker-alt"></i><p><strong>{{ __('storefront.common.address') }}:</strong> {{ $storefront->address }}</p></div>@endif @if($storefront->city)<div class="contact-line"><i class="fas fa-city"></i><p><strong>{{ __('storefront.common.city') }}:</strong> {{ $storefront->city }}</p></div>@endif</aside></div></section>
</main><footer class="footer"><div class="shell">{{ $storefront->display_name }} · {{ __('storefront.common.marketplace') }}</div></footer>
@endsection
