@extends('storefront.public.layout')
@section('title', __('storefront.clothing.catalog_title').' — '.$storefront->display_name)
@push('styles')
.filters{margin:-24px auto 30px;position:relative}.filter-grid{display:grid;grid-template-columns:2fr 1fr auto;gap:12px}.product-card{padding:0;overflow:hidden}.photo{height:235px;background:linear-gradient(135deg,#e2eee9,#f2f7f4);display:grid;place-items:center;font-size:3rem}.photo img{width:100%;height:100%;object-fit:cover}.product-body{padding:19px}.colors{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.product-body .btn{display:block;margin-top:14px}@media(max-width:600px){.filter-grid{grid-template-columns:1fr}}
@endpush
@section('body')
<nav class="nav"><div class="shell"><a class="nav-brand" href="{{ route('storefront.show',$storefront) }}">{{ $storefront->display_name }}</a><div class="nav-actions">@include('storefront.public.partials.language-switch')<a class="nav-link" href="{{ route('storefront.cart.show',$storefront) }}">{{ __('storefront.clothing.cart') }}</a><a class="nav-link" href="{{ route('storefront.show',$storefront) }}">{{ __('storefront.common.shop_home') }}</a></div></div></nav>
<header class="hero"><div class="shell"><h1>{{ __('storefront.clothing.catalog_title') }}</h1><p>{{ __('storefront.clothing.catalog_intro') }}</p></div></header>
<main class="shell section">
<form class="card filters" method="GET"><div class="filter-grid"><input class="control" name="q" value="{{ $filters['q'] ?? '' }}" aria-label="{{ __('storefront.clothing.search_label') }}" placeholder="{{ __('storefront.clothing.search_placeholder') }}"><select class="control" name="color" aria-label="{{ __('storefront.clothing.color_label') }}"><option value="">{{ __('storefront.clothing.all_colors') }}</option>@foreach($colors as $color)<option value="{{ $color }}" @selected(($filters['color']??'')===$color)>{{ $color }}</option>@endforeach</select><button class="btn">{{ __('storefront.common.search') }}</button></div></form>
<div class="grid">@forelse($listings as $listing)
@php($image=$listing->cloth->images->first(fn($item)=>$item->image_url)) @php($available=(float)$listing->cloth->colors->sum(fn($color)=>$color->reservableLength()))
<article class="card product-card"><div class="photo">@if($image)<img src="{{ $image->image_url }}" alt="{{ $listing->display_name }}">@else<span>🧵</span>@endif</div><div class="product-body">@if($listing->is_featured)<div class="featured">{{ __('storefront.clothing.featured') }}</div>@endif<h2>{{ $listing->display_name }}</h2><div class="muted">{{ $listing->cloth->brand->name ?? __('storefront.clothing.no_brand') }} · {{ $listing->cloth->type->name ?? __('storefront.clothing.fabric') }}</div><div class="price">{{ __('storefront.common.rs') }} {{ number_format((float)($listing->cloth->sale_price ?: $listing->cloth->price),2) }} {{ __('storefront.clothing.per_metre') }}</div><div>{{ $available>0 ? __('storefront.clothing.available',['amount'=>number_format($available,2)]) : __('storefront.clothing.out_of_stock') }}</div><div class="colors">@foreach($listing->cloth->colors as $color)<span class="pill">{{ $color->color }} — {{ number_format($color->reservableLength(),2) }}m</span>@endforeach</div><a class="btn" href="{{ route('storefront.clothing.show',[$storefront,$listing]) }}">{{ __('storefront.clothing.view_details') }}</a></div></article>
@empty<div class="card empty" style="grid-column:1/-1"><h2>{{ __('storefront.clothing.empty_title') }}</h2><p>{{ __('storefront.clothing.empty_text') }}</p></div>@endforelse</div>
@if($listings->hasPages())<div style="margin-top:25px">{{ $listings->links() }}</div>@endif
</main>
@endsection
