@extends('main')
@section('content')
<style>
    .activity-page{min-height:calc(100vh - 70px);background:#f5f7fa}.activity-hero{padding:1.6rem;border-radius:20px;background:linear-gradient(135deg,#1f3a5f,#3568a8);color:#fff}.activity-hero h1{color:#fff!important}.summary-card{height:100%;padding:1rem;border:0;border-radius:15px;background:#fff;box-shadow:0 8px 24px rgba(31,45,61,.07)}.activity-card{border:0;border-radius:18px;box-shadow:0 10px 28px rgba(31,45,61,.08)}.activity-time{white-space:nowrap}.actor-avatar{display:inline-grid;place-items:center;width:34px;height:34px;margin-left:.5rem;border-radius:10px;background:#e7f0ff;color:#1769aa;font-weight:800}.route-code{direction:ltr;text-align:left;font:12px Consolas,monospace;color:#718096}
</style>
<section class="main-content activity-page"><div class="container-fluid py-4 px-lg-5">
    <div class="activity-hero mb-4"><span class="badge badge-light text-primary mb-2">محفوظ کاروباری ریکارڈ</span><h1 class="h3 font-weight-bold mb-2">ملازمین کی سرگرمی</h1><p class="mb-0 text-white-50">دیکھیں کہ کس ملازم نے کب کون سی کامیاب تبدیلی کی۔ پاس ورڈ اور فارم کی خفیہ معلومات یہاں محفوظ نہیں کی جاتیں۔</p></div>
    <div class="row mb-4"><div class="col-md-4 mb-3"><div class="summary-card"><small class="text-muted">آج کی سرگرمیاں</small><strong class="d-block h3 mb-0 text-primary">{{ number_format($todayCount) }}</strong></div></div><div class="col-md-4 mb-3"><div class="summary-card"><small class="text-muted">آج فعال صارفین</small><strong class="d-block h3 mb-0 text-success">{{ number_format($actorCount) }}</strong></div></div><div class="col-md-4 mb-3"><div class="summary-card"><small class="text-muted">کل محفوظ سرگرمیاں</small><strong class="d-block h3 mb-0">{{ number_format($logs->total()) }}</strong></div></div></div>
    <div class="card activity-card mb-4"><div class="card-body p-4"><form method="GET" class="row align-items-end"><div class="col-lg-3 form-group"><label>ملازم</label><select class="form-control" name="employee"><option value="">تمام صارفین</option>@foreach($members as $member)<option value="{{ $member->id }}" {{ (string) request('employee') === (string) $member->id ? 'selected' : '' }}>{{ $member->name }}{{ $member->username ? ' (@'.$member->username.')' : '' }}</option>@endforeach</select></div><div class="col-lg-2 form-group"><label>شروع تاریخ</label><input type="date" class="form-control" name="from" value="{{ request('from') }}"></div><div class="col-lg-2 form-group"><label>آخری تاریخ</label><input type="date" class="form-control" name="to" value="{{ request('to') }}"></div><div class="col-lg-3 form-group"><label>روٹ یا کارروائی</label><input class="form-control" name="action" value="{{ request('action') }}" dir="ltr" placeholder="مثلاً purchases"></div><div class="col-lg-2 form-group"><button class="btn btn-primary btn-block">فلٹر کریں</button><a class="btn btn-outline-success btn-block" href="{{ route('admin.activity.export', request()->query()) }}">CSV ڈاؤن لوڈ</a></div></form></div></div>
    <div class="card activity-card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="thead-light"><tr><th>وقت</th><th>صارف</th><th>شعبہ</th><th>کارروائی</th><th>حوالہ</th></tr></thead><tbody>@forelse($logs as $log)<tr><td class="activity-time"><strong>{{ $log->created_at->format('d-m-Y') }}</strong><br><small class="text-muted" dir="ltr">{{ $log->created_at->format('h:i A') }}</small></td><td><span class="actor-avatar">{{ mb_substr($log->actor?->name ?? 'S', 0, 1) }}</span><strong>{{ $log->actor?->name ?? 'سسٹم' }}</strong>@if($log->actor?->username)<br><small class="text-muted" dir="ltr">{{ '@'.$log->actor->username }}</small>@endif</td><td><span class="badge badge-info">{{ $log->areaLabel() }}</span></td><td>{{ $log->actionDescription() }}<br><small class="text-muted" dir="ltr">{{ $log->method }}</small></td><td><div class="route-code">{{ $log->route_name ?: $log->path }}</div>@if($log->route_parameters)<small class="text-muted" dir="ltr">{{ collect($log->route_parameters)->map(fn($value,$key) => $key.':'.(is_array($value) ? ($value['id'] ?? '') : $value))->implode(' · ') }}</small>@endif</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-5">منتخب مدت میں کوئی سرگرمی موجود نہیں۔</td></tr>@endforelse</tbody></table></div>@if($logs->hasPages())<div class="p-3">{{ $logs->links() }}</div>@endif</div></div>
</div></section>
@endsection
