@extends('main')
@section('content')
<style>
    .team-page{background:#f5f7fa;min-height:calc(100vh - 70px)}.team-hero{background:linear-gradient(135deg,#102a43,#1769aa);color:#fff;border-radius:20px;padding:1.7rem}.team-hero h1,.team-hero strong{color:#fff!important}.team-hero p,.team-hero small{color:rgba(255,255,255,.78)!important}.team-card{border:0;border-radius:18px;box-shadow:0 10px 28px rgba(31,45,61,.08)}.permission-box{border:1px solid #dfe7f0;border-radius:12px;padding:.8rem;height:100%;background:#fbfdff}.status-dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-left:.35rem}.status-on{background:#28a745}.status-off{background:#dc3545}
</style>
<section class="main-content team-page"><div class="container-fluid py-4 px-lg-5">
    <div class="team-hero mb-4"><div class="row align-items-center"><div class="col-lg-8"><span class="badge badge-light text-primary mb-2">کاروباری ٹیم</span><h1 class="h3 font-weight-bold">ملازمین، رولز اور اجازتیں</h1><p class="mb-0 text-white-50">ہر ملازم کو صرف اسی ورک اسپیس اور معلومات تک رسائی دیں جو اس کے کام کے لیے ضروری ہے۔</p></div><div class="col-lg-4 text-lg-left mt-3 mt-lg-0"><strong>{{ $business->name }}</strong><br><small>{{ $business->members->count() }} ملازم</small></div></div></div>

    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><strong>براہ کرم درج ذیل معلومات درست کریں:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <div class="card team-card mb-4"><div class="card-body p-4"><div class="row align-items-center"><div class="col-lg-7"><h2 class="h5 font-weight-bold mb-1">ملازمین کے پاس ورڈ کی میعاد</h2><p class="text-muted mb-3 mb-lg-0">اختیاری مدت مقرر کریں۔ مدت ختم ہونے پر ملازم کو کام جاری رکھنے سے پہلے نیا پاس ورڈ بنانا ہوگا۔ پالیسی تبدیل کرنے سے موجودہ ملازمین کو مکمل نئی مدت ملے گی۔</p></div><div class="col-lg-5"><form method="POST" action="{{ route('admin.team.password-policy.update') }}">@csrf @method('PUT')<div class="input-group"><select class="form-control" name="password_expiry_days"><option value="0" {{ ! $business->password_expiry_days ? 'selected' : '' }}>بند — پاس ورڈ کی میعاد مقرر نہیں</option>@foreach([30, 60, 90, 180, 365] as $days)<option value="{{ $days }}" {{ (int) $business->password_expiry_days === $days ? 'selected' : '' }}>{{ $days }} دن</option>@endforeach</select><div class="input-group-append"><button class="btn btn-primary">پالیسی محفوظ کریں</button></div></div></form></div></div></div></div>

    <div class="row">
        <div class="col-xl-5 mb-4"><div class="card team-card"><div class="card-body p-4"><h2 class="h5 font-weight-bold mb-3">نیا رول بنائیں</h2><form method="POST" action="{{ route('admin.team.roles.store') }}">@csrf
            <div class="form-group"><label>رول کا نام</label><input class="form-control" name="name" value="{{ old('name') }}" placeholder="مثلاً سیلز پرسن" required></div>
            <label class="d-block">اجازتیں</label><div class="row">@foreach($permissions as $key => $label)<div class="col-12 mb-2"><label class="permission-box d-flex align-items-center mb-0"><input type="checkbox" name="permissions[]" value="{{ $key }}" class="ml-2" {{ in_array($key, old('permissions', []), true) ? 'checked' : '' }}><span>{{ $label }}</span></label></div>@endforeach</div>
            <button class="btn btn-primary btn-block mt-2"><i class="fas fa-user-shield ml-1"></i> رول محفوظ کریں</button>
        </form></div></div></div>
        <div class="col-xl-7 mb-4"><div class="card team-card"><div class="card-body p-4"><h2 class="h5 font-weight-bold mb-3">نیا ملازم شامل کریں</h2>
            @if($business->roles->isEmpty())<div class="alert alert-info">ملازم شامل کرنے سے پہلے کم از کم ایک رول بنائیں۔</div>@else<form method="POST" action="{{ route('admin.team.employees.store') }}">@csrf<div class="row">
                <div class="col-md-6 form-group"><label>ملازم کا نام</label><input class="form-control" name="name" value="{{ old('name') }}" required></div>
                <div class="col-md-6 form-group"><label>عہدہ</label><input class="form-control" name="job_title" value="{{ old('job_title') }}" placeholder="مثلاً کاؤنٹر سیلز"></div>
                <div class="col-md-6 form-group"><label>یوزر نیم</label><input class="form-control" name="username" value="{{ old('username') }}" dir="ltr" placeholder="مثلاً sale.ahmad" required></div>
                <div class="col-md-6 form-group"><label>ای میل</label><input type="email" class="form-control text-left" dir="ltr" name="email" value="{{ old('email') }}" required></div>
                <div class="col-md-6 form-group"><label>فون نمبر</label><input class="form-control" name="phone" value="{{ old('phone') }}" dir="ltr"></div>
                <div class="col-md-6 form-group"><label for="employee-temporary-password">عارضی پاس ورڈ</label><input id="employee-temporary-password" type="password" class="form-control" name="password" minlength="8" required autocomplete="new-password"><small class="form-text text-muted">ملازم پہلے لاگ اِن پر اپنا نیا پاس ورڈ بنائے گا۔</small>@include('team.partials.password-strength', ['inputId' => 'employee-temporary-password'])</div>
                <div class="col-12 form-group"><label>پتہ</label><textarea class="form-control" name="address" rows="2">{{ old('address') }}</textarea></div>
                <div class="col-md-8 form-group"><label>رول</label><select class="form-control" name="business_role_id" required><option value="">رول منتخب کریں</option>@foreach($business->roles as $role)<option value="{{ $role->id }}" {{ (string) old('business_role_id') === (string) $role->id ? 'selected' : '' }}>{{ $role->name }}</option>@endforeach</select></div>
                <div class="col-md-4 d-flex align-items-end form-group"><button class="btn btn-success btn-block"><i class="fas fa-user-plus ml-1"></i> ملازم شامل کریں</button></div>
            </div></form>@endif
        </div></div></div>
    </div>

    <div class="card team-card mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 font-weight-bold mb-0">موجودہ ملازمین</h2><span class="badge badge-secondary">{{ $business->members->count() }}</span></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>ملازم</th><th>عہدہ</th><th>رول</th><th>حالت</th><th></th></tr></thead><tbody>
        @forelse($business->members as $employee)<tr><td><strong>{{ $employee->name }}</strong><br><small class="text-muted" dir="ltr">{{ '@'.$employee->username }} · {{ $employee->email }}</small>@if($employee->phone)<br><small dir="ltr">{{ $employee->phone }}</small>@endif</td><td>{{ $employee->job_title ?: '—' }}</td><td>{{ $employee->businessRole?->name ?: 'رول مقرر نہیں' }}</td><td><span class="status-dot {{ $employee->employee_active ? 'status-on' : 'status-off' }}"></span>{{ $employee->employee_active ? ($employee->must_change_password ? 'عارضی پاس ورڈ' : ($employee->employeePasswordExpired() ? 'پاس ورڈ کی میعاد ختم' : 'فعال')) : 'غیر فعال' }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.team.employees.edit', $employee) }}">ترمیم</a></td></tr>
        @empty<tr><td colspan="5" class="text-center text-muted py-4">ابھی کوئی ملازم شامل نہیں کیا گیا۔</td></tr>@endforelse
    </tbody></table></div></div></div>

    <div class="card team-card"><div class="card-body p-4"><h2 class="h5 font-weight-bold mb-3">کاروباری رولز</h2><div class="row">@forelse($business->roles as $role)<div class="col-lg-4 mb-3"><div class="permission-box"><div class="d-flex justify-content-between"><strong>{{ $role->name }}</strong><span class="badge badge-light">{{ $role->users_count }} ملازم</span></div><div class="my-3">@foreach($role->permissions as $permission)<span class="badge badge-info mb-1">{{ \App\Models\BusinessRole::PERMISSIONS[$permission] ?? $permission }}</span>@endforeach</div><div class="d-flex"><a class="btn btn-sm btn-outline-primary ml-2" href="{{ route('admin.team.roles.edit', $role) }}">ترمیم</a><form method="POST" action="{{ route('admin.team.roles.destroy', $role) }}" onsubmit="return confirm('کیا آپ یہ رول حذف کرنا چاہتے ہیں؟')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" {{ $role->users_count ? 'disabled' : '' }}>حذف</button></form></div></div></div>@empty<div class="col-12 text-muted">ابھی کوئی رول نہیں بنایا گیا۔</div>@endforelse</div></div></div>
</div></section>
@endsection
