/* Fabric-first storefront: shared by the home, catalog and checkout pages. */
:root{--ink:{{ $configuredText === '#17372e' ? '#141b34' : $configuredText }};--muted:#5a6180;--line:#d9dce6;--shop-background:{{ $configuredBackground === '#f5f7f6' ? '#f1f2f5' : $configuredBackground }};--shop-surface:{{ $configuredSurface }};--primary:{{ $configuredPrimary === '#126b4f' ? '#1e6b52' : $configuredPrimary }};--primary-dark:{{ $configuredPrimary === '#126b4f' ? '#1b2547' : $configuredPrimary }};--accent:{{ $configuredAccent === '#d98a12' ? '#e8a317' : $configuredAccent }}}
body{font-size:16px}.shop-nav .nav-brand{font-size:1.2rem}.shop-nav .logo{background:#1b2547;color:#e8a317;border-radius:12px}.shop-nav .nav-link{border-color:var(--line);border-radius:999px;gap:7px}.shop-nav .locale-switch{gap:2px;padding:3px;background:#f1f2f5;border:1px solid var(--line);border-radius:999px}.shop-nav .locale-switch>a{border-radius:999px;padding:5px 12px}.shop-nav .locale-switch>a.active{background:#1b2547;color:#fff}.shop-nav .locale-switch>span{display:none}
.category-nav{box-shadow:none}.category-link,.category-drop summary{font-size:.85rem;min-height:44px}.category-menu a{font-size:.88rem;min-height:44px}.category-menu{max-height:60vh;overflow:auto}.shop-search input{background:#f1f2f5;border-color:var(--line)}.shop-search{min-width:0}.shop-header .menu-scroll{flex-wrap:wrap}.shop-search input,.shop-search button{min-height:46px}
.card{box-shadow:0 3px 12px #141b3405}.hero{background:#1b2547}.hero p{color:#e0e4f0}.shop-footer{background:#1b2547}.btn,.control{border-radius:12px}.product-body h2{font-size:1.15rem}.product-body .muted{font-size:.9rem}
a:focus-visible,button:focus-visible,summary:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #e8a317;outline-offset:3px}
html[lang="ur"] body{font-family:"Noto Nastaliq Urdu",Tahoma,sans-serif}html[lang="ur"] .category-link,html[lang="ur"] .category-drop summary{line-height:2.2}
@media(max-width:1000px){.shop-header .menu-scroll{overflow:visible}.category-menu{top:100%;inset-inline:0}}
@media(max-width:600px){.shop-nav .nav-brand{font-size:.9rem}.shop-nav .locale-switch>a{padding:4px 7px;min-width:38px}.shop-nav .nav-actions{gap:4px}.category-link,.category-drop summary{font-size:.78rem;padding-inline:8px}.shop-nav .logo{margin-inline-end:5px;width:34px;height:34px}.shop-nav .nav-link{padding:7px}.shop-nav .nav-brand>span:last-child{max-width:120px}}
