@php
    $configuredPrimary = preg_match('/^#[0-9a-f]{6}$/i', (string) $storefront->theme_primary_color) ? $storefront->theme_primary_color : '#126b4f';
    $configuredAccent = preg_match('/^#[0-9a-f]{6}$/i', (string) $storefront->theme_accent_color) ? $storefront->theme_accent_color : '#d98a12';
    $configuredBackground = preg_match('/^#[0-9a-f]{6}$/i', (string) $storefront->theme_background_color) ? $storefront->theme_background_color : '#f5f7f6';
    $configuredSurface = preg_match('/^#[0-9a-f]{6}$/i', (string) $storefront->theme_surface_color) ? $storefront->theme_surface_color : '#ffffff';
    $configuredText = preg_match('/^#[0-9a-f]{6}$/i', (string) $storefront->theme_text_color) ? $storefront->theme_text_color : '#17372e';
    $configuredRadius = ['square' => '3px', 'rounded' => '24px'][$storefront->corner_style] ?? '14px';
    $configuredFont = [
        'classic' => "Georgia, 'Noto Nastaliq Urdu', serif",
        'minimal' => "Arial, 'Noto Sans Arabic', sans-serif",
    ][$storefront->font_style] ?? "Inter, 'Noto Nastaliq Urdu', system-ui, sans-serif";
@endphp
:root{--primary:{{ $configuredPrimary }};--primary-dark:{{ $configuredPrimary }};--accent:{{ $configuredAccent }};--ink:{{ $configuredText }};--shop-background:{{ $configuredBackground }};--shop-surface:{{ $configuredSurface }};--shop-radius:{{ $configuredRadius }};--shop-font:{!! $configuredFont !!}}
body,body:lang(en),body:lang(ur){color:var(--ink);background:var(--shop-background);font-family:var(--shop-font)}.card,.shop-nav,.category-nav,.benefits{background:var(--shop-surface)}.card,.control,.btn,.nav-link,.category-link,.category-drop summary{border-radius:var(--shop-radius)}
.shop-announcement{padding:7px 14px;color:#fff;background:var(--primary);text-align:center;font-size:.72rem;font-weight:800}.shop-header{position:relative;z-index:30}.shop-header.is-sticky{position:sticky;top:0}.logo{width:42px;height:42px;margin-inline-end:8px;border-radius:var(--shop-radius);object-fit:cover;background:#dcece5}
.shop-nav .shell{min-height:68px;flex-wrap:nowrap}.shop-nav .nav-brand{min-width:0;font-size:.92rem}.shop-nav .nav-brand>span:last-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.shop-nav .nav-actions{flex-wrap:nowrap}.shop-nav .nav-link{min-height:40px;white-space:nowrap}.shop-search{display:flex;min-width:260px;max-width:420px;margin:0}.shop-search input{width:100%;min-height:40px;padding:7px 12px;border:1px solid #cbd9d3;border-radius:10px 0 0 10px;background:#f8fbfa;font:inherit}.shop-search button{min-width:45px;border:0;border-radius:0 10px 10px 0;color:#fff;background:var(--primary);cursor:pointer}.cart-link{position:relative}
html[dir="rtl"] .shop-search input{border-radius:0 10px 10px 0}html[dir="rtl"] .shop-search button{border-radius:10px 0 0 10px}
.category-nav{border-bottom:1px solid var(--line);background:var(--shop-surface);box-shadow:0 5px 16px rgba(19,55,43,.08)}.category-nav .shell{min-height:56px;display:grid;grid-template-columns:minmax(0,1fr) minmax(270px,420px);align-items:center;gap:14px;overflow:visible}.menu-scroll{min-width:0;display:flex;align-items:center;gap:4px;overflow:visible}.header-layout-search_first .shop-search{order:1}.header-layout-search_first .menu-scroll{order:2}.category-link,.category-drop summary{min-height:38px;display:inline-flex;align-items:center;gap:7px;padding:6px 10px;border-radius:8px;color:var(--ink);text-decoration:none;font-size:.68rem;font-weight:800;cursor:pointer;list-style:none;white-space:nowrap}.category-link:hover,.category-link.is-active,.category-drop[open] summary{color:var(--primary);background:#eaf3ef}.category-drop{position:relative}.category-drop summary::-webkit-details-marker{display:none}.category-menu{position:absolute;z-index:8;top:44px;inset-inline-start:0;width:260px;padding:10px;border:1px solid var(--line);border-radius:12px;background:var(--shop-surface);box-shadow:0 14px 34px rgba(19,55,43,.16)}.category-menu a{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px 10px;border-radius:7px;color:var(--ink);font-size:.68rem;text-decoration:none}.category-menu a:hover{color:var(--primary);background:#f0f6f3}
@media(max-width:1000px){.category-nav .shell{grid-template-columns:1fr;gap:7px;padding-block:7px}.menu-scroll{overflow-x:auto;scrollbar-width:none}.menu-scroll::-webkit-scrollbar{display:none}.shop-search{width:100%;max-width:none}.category-drop{position:static}.category-menu{inset-inline:14px;width:auto}}
@media(max-width:600px){.shop-nav .shell{min-height:62px;gap:7px;padding-block:7px}.shop-nav .nav-brand{font-size:.78rem}.logo{width:38px;height:38px}.shop-nav .nav-actions{gap:5px}.shop-nav .nav-link{min-height:38px;padding:6px 9px}.all-shops-link span,.cart-link span{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0)}.category-nav .shell{padding-block:6px}.category-link,.category-drop summary{padding-inline:9px}.shop-announcement{font-size:.65rem}}
.shop-footer{padding:36px 0 16px;color:rgba(255,255,255,.82);background:color-mix(in srgb,var(--primary) 72%,#071c16)}.shop-footer-grid{display:grid;grid-template-columns:minmax(260px,1.3fr) minmax(170px,.7fr) minmax(200px,.8fr);gap:34px}.shop-footer-brand a{display:flex;align-items:center;gap:10px;color:#fff;text-decoration:none;font-size:1.15rem}.shop-footer-brand img{width:46px;height:46px;border-radius:var(--shop-radius);object-fit:cover}.shop-footer-brand p{max-width:540px;margin:9px 0 0}.shop-footer-links,.shop-footer-contact{display:flex;align-items:flex-start;flex-direction:column;gap:8px}.shop-footer a{color:#fff;text-decoration:none}.shop-socials{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px}.shop-socials a{padding:4px 9px;border:1px solid rgba(255,255,255,.28);border-radius:999px;font-size:.68rem}.shop-footer-bottom{display:flex;justify-content:space-between;gap:15px;margin-top:25px;padding-top:14px;border-top:1px solid rgba(255,255,255,.16);font-size:.7rem}.shop-footer.style-simple{padding-top:20px}.shop-footer.style-simple .shop-footer-grid{grid-template-columns:1fr}.shop-footer.style-simple .shop-footer-brand{display:flex;align-items:center;justify-content:space-between;gap:20px}.shop-footer.style-simple .shop-footer-brand p{margin:0}.shop-footer.style-brand .shop-footer-brand strong{font-size:1.55rem}.shop-footer.style-brand .shop-footer-grid{grid-template-columns:minmax(300px,1.6fr) minmax(180px,.6fr) minmax(200px,.7fr)}
@media(max-width:760px){.shop-footer-grid,.shop-footer.style-brand .shop-footer-grid{grid-template-columns:1fr;gap:22px}.shop-footer.style-simple .shop-footer-brand{align-items:flex-start;flex-direction:column}.shop-footer-bottom{align-items:flex-start;flex-direction:column}}
