<article data-order-item="{{ $item->id }}">
    <div class="co-grid-row {{ $item->type==='tailoring' ? 'is-tailoring' : '' }}" data-display-row="{{ $item->id }}">
        <div class="co-cell-main" data-label="آئٹم"><strong>@if($item->type==='cloth'){{ $item->cloth?->name }} · {{ $item->cloth?->brand?->name }} · {{ $item->cloth?->type?->name }}@else{{ $item->measurementTemplate?->name ?: 'سلائی' }} · {{ $item->measurementProfile?->name }}@endif</strong>@if($item->item_serial)<small dir="ltr">{{ $item->item_serial }}</small>@endif<span class="co-row-status {{ $item->status==='confirmed' ? 'is-confirmed' : '' }}">{{ $item->status==='confirmed' ? 'تصدیق شدہ' : 'تصدیق باقی' }}</span></div>
        <div data-label="رنگ / تفصیل">@if($item->type==='cloth'){{ data_get($item->details,'color') ?: 'رنگ لاگو نہیں' }}@else مکمل: {{ $item->due_date?->format('d-m-Y') }}@endif</div>
        <div data-label="میٹر / تعداد">@if($item->type==='cloth')@if($item->cloth?->sellsPerSuit()){{ (int)$item->quantity }} سوٹ × @endif{{ number_format((float)$item->length,2) }} میٹر @else{{ (int)$item->quantity }} سوٹ@endif</div>
        <div class="co-cell-money" data-label="کل قیمت">Rs. {{ number_format((float)$item->line_total,2) }}</div>
        <div class="co-cell-note" data-label="نوٹ">{{ $item->note ?: '—' }}</div>
        <div class="co-grid-actions">@if($item->status==='confirmed')<a class="co-print-action" target="_blank" href="{{ route('admin.counter-orders.items.print',[$counterOrder,$item]) }}" title="{{ $item->type==='tailoring' ? 'سلائی رسید' : 'کپڑے کی رسید' }}" aria-label="{{ $item->type==='tailoring' ? 'سلائی رسید' : 'کپڑے کی رسید' }}"><i class="fas fa-print"></i><span>{{ $item->type==='tailoring' ? 'سلائی رسید' : 'رسید' }}</span></a>@if($item->type==='tailoring' && $canAddTailoring && $item->source_record_type==='tailoring_order' && $item->source_record_id)<a class="co-print-action" target="_blank" rel="noopener" href="{{ route('admin.order-prints', ['id' => $item->source_record_id, 'serial_only' => 1]) }}"><i class="fas fa-tag"></i><span>صرف سیریل پرنٹ</span></a>@endif @elseif(($item->type==='cloth' && $canAddCloth) || ($item->type==='tailoring' && $canAddTailoring))<button class="co-edit" type="button" @if($item->type==='cloth') data-inline-edit="co-edit-cloth-{{ $item->id }}" @else data-toggle="modal" data-target="#editItemModal{{ $item->id }}" @endif title="تبدیل کریں" aria-label="آئٹم تبدیل کریں"><i class="fas fa-pen"></i></button><form method="POST" action="{{ route('admin.counter-orders.items.destroy',[$counterOrder,$item]) }}">@csrf @method('DELETE')<button class="co-remove" type="submit" title="ہٹائیں" aria-label="آئٹم ہٹائیں"><i class="fas fa-trash-alt"></i></button></form>@endif</div>
    </div>
    @if($item->type==='cloth' && $item->status==='draft' && $canAddCloth)
    <form id="co-edit-cloth-{{ $item->id }}" class="co-grid-row co-cloth-form co-ajax-row-form is-new" method="POST" action="{{ route('admin.counter-orders.items.update',[$counterOrder,$item]) }}" data-basis="{{ data_get($item->details,'sale_price_basis',$item->cloth?->sale_price_basis) }}" data-unit-price="{{ $item->unit_price }}" hidden>@csrf @method('PATCH')
        <div class="co-cell-main" data-label="آئٹم"><div class="co-readonly">{{ $item->cloth?->name }} · {{ $item->cloth?->brand?->name }} · {{ $item->cloth?->type?->name }}</div></div>
        <div data-label="رنگ"><select id="edit-color-{{ $item->id }}" class="form-control" name="color" aria-label="رنگ">@if(!$item->cloth?->hasSelectableColors())<option value="">رنگ لاگو نہیں</option>@endif @foreach($item->cloth?->selectableColorNames() ?? [] as $color)<option value="{{ $color }}" @selected(data_get($item->details,'color')===$color)>{{ $color }}</option>@endforeach</select></div>
        <div data-label="میٹر / تعداد"><input id="edit-length-{{ $item->id }}" class="form-control co-cloth-length" type="number" name="length" value="{{ $item->length }}" min="0.01" step="0.01" aria-label="لمبائی میٹر" required><input id="edit-quantity-{{ $item->id }}" class="form-control co-cloth-quantity co-suit-only" type="number" name="quantity" value="{{ (int)$item->quantity }}" min="1" step="1" aria-label="سوٹ کی تعداد" @if(!$item->cloth?->sellsPerSuit()) hidden @endif></div>
        <div data-label="کل قیمت"><input id="edit-total-{{ $item->id }}" class="form-control co-cloth-total" type="number" name="total_price" value="{{ $item->line_total }}" min="0" step="0.01" aria-label="کل قیمت" required></div>
        <div data-label="نوٹ"><input id="edit-note-{{ $item->id }}" class="form-control" name="note" value="{{ $item->note }}" maxlength="1000" aria-label="نوٹ" placeholder="اختیاری نوٹ"></div>
        <div class="co-grid-actions"><button class="co-grid-save" type="submit" title="محفوظ کریں" aria-label="محفوظ کریں"><i class="fas fa-check"></i></button><button class="co-grid-cancel" type="button" data-inline-cancel="co-edit-cloth-{{ $item->id }}" title="منسوخ" aria-label="منسوخ"><i class="fas fa-times"></i></button></div>
    </form>
    @endif
</article>
