@php($rules=$collection?->rules ?? [])
<div class="form-row">
    <div class="form-group col-md-4"><label>نام — اردو</label><input name="name_ur" dir="rtl" maxlength="180" class="form-control" value="{{ old('name_ur',$collection?->name_ur) }}"></div>
    <div class="form-group col-md-4"><label>Name — English</label><input name="name_en" dir="ltr" maxlength="180" class="form-control text-left" value="{{ old('name_en',$collection?->name_en) }}"></div>
    <div class="form-group col-md-4"><label>URL slug</label><input name="slug" dir="ltr" maxlength="100" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" class="form-control text-left" value="{{ old('slug',$collection?->slug) }}" placeholder="summer-collection"></div>
</div>
<div class="form-row">
    <div class="form-group col-md-6"><label>تعارف — اردو</label><textarea name="description_ur" rows="2" maxlength="1000" class="form-control">{{ old('description_ur',$collection?->description_ur) }}</textarea></div>
    <div class="form-group col-md-6"><label>Description — English</label><textarea name="description_en" dir="ltr" rows="2" maxlength="1000" class="form-control text-left">{{ old('description_en',$collection?->description_en) }}</textarea></div>
</div>
<div class="form-row">
    <div class="form-group col-md-4"><label>کلیکشن کی بنیاد</label><select name="source_type" class="form-control collection-source"><option value="manual" @selected(($collection?->source_type??'manual')==='manual')>منتخب مصنوعات</option><option value="category" @selected($collection?->source_type==='category')>کیٹیگری</option><option value="brand" @selected($collection?->source_type==='brand')>برانڈ</option><option value="tag" @selected($collection?->source_type==='tag')>ٹیگ</option><option value="sale" @selected($collection?->source_type==='sale')>سیل / رعایت</option><option value="featured" @selected($collection?->source_type==='featured')>نمایاں مصنوعات</option><option value="new_arrivals" @selected($collection?->source_type==='new_arrivals')>نئی مصنوعات</option><option value="in_stock" @selected($collection?->source_type==='in_stock')>اسٹاک میں</option><option value="all" @selected($collection?->source_type==='all')>تمام مصنوعات</option></select></div>
    <div class="form-group col-md-4"><label>ترتیب</label><select name="sort_mode" class="form-control"><option value="manual" @selected(($collection?->sort_mode??'manual')==='manual')>دستی ترتیب</option><option value="newest" @selected($collection?->sort_mode==='newest')>نیا پہلے</option><option value="featured" @selected($collection?->sort_mode==='featured')>نمایاں پہلے</option><option value="price_asc" @selected($collection?->sort_mode==='price_asc')>قیمت کم سے زیادہ</option><option value="price_desc" @selected($collection?->sort_mode==='price_desc')>قیمت زیادہ سے کم</option></select></div>
    <div class="form-group col-md-2"><label>ترتیب نمبر</label><input type="number" name="sort_order" min="0" max="9999" class="form-control" value="{{ old('sort_order',$collection?->sort_order??0) }}"></div>
    <div class="form-group col-md-2 pt-md-4"><label><input type="checkbox" name="is_published" value="1" @checked(old('is_published',$collection?->is_published))> شائع کریں</label></div>
</div>
<div class="rule-panels border rounded p-3 mb-3 bg-light">
    <div data-source="manual"><label class="d-block font-weight-bold">مصنوعات منتخب کریں</label><div class="choice-grid">@foreach($listings as $listing)<label><input type="checkbox" name="listing_ids[]" value="{{ $listing->id }}" @checked(in_array($listing->id,$rules['listing_ids']??[]))> {{ $listing->localizedName('ur') }} / {{ $listing->localizedName('en') }}</label>@endforeach</div></div>
    <div data-source="category"><label class="d-block font-weight-bold">کیٹیگری منتخب کریں</label><div class="choice-grid">@foreach($types as $type)<label><input type="checkbox" name="category_ids[]" value="{{ $type->id }}" @checked(in_array($type->id,$rules['category_ids']??[]))> {{ $type->localizedName('ur') }} / {{ $type->localizedName('en') }}</label>@endforeach</div></div>
    <div data-source="brand"><label class="d-block font-weight-bold">برانڈ منتخب کریں</label><div class="choice-grid">@foreach($brands as $brand)<label><input type="checkbox" name="brand_ids[]" value="{{ $brand->id }}" @checked(in_array($brand->id,$rules['brand_ids']??[]))> {{ $brand->name }}</label>@endforeach</div></div>
    <div data-source="tag"><label class="font-weight-bold">ٹیگز</label><input name="collection_tags" class="form-control" value="{{ old('collection_tags',collect($rules['tags']??[])->join(', ')) }}" placeholder="summer, wedding"></div>
    <div data-source="automatic"><p class="mb-0 text-muted">یہ کلیکشن موجودہ پروڈکٹ ڈیٹا سے خودکار طور پر اپ ڈیٹ ہوتی رہے گی۔</p></div>
</div>
<div class="form-row align-items-end"><div class="form-group col-md-3"><label>کم از کم قیمت</label><input type="number" name="min_price" min="0" max="10000000" class="form-control" value="{{ old('min_price',$rules['min_price']??'') }}"></div><div class="form-group col-md-3"><label>زیادہ سے زیادہ قیمت</label><input type="number" name="max_price" min="0" max="10000000" class="form-control" value="{{ old('max_price',$rules['max_price']??'') }}"></div><div class="form-group col-md-4"><label><input type="checkbox" name="online_order_enabled" value="1" @checked(old('online_order_enabled',$rules['online_order_enabled']??false))> صرف آن لائن آرڈر والی مصنوعات</label></div><div class="form-group col-md-2"><button class="btn btn-primary btn-block">محفوظ کریں</button></div></div>
