<div class="form-row align-items-end">
<div class="form-group col-lg-2 col-md-4"><label>لیبل — اردو</label><input name="label_ur" class="form-control" value="{{ old('label_ur',$menuItem?->label_ur) }}"></div>
<div class="form-group col-lg-2 col-md-4"><label>Label — English</label><input name="label_en" dir="ltr" class="form-control text-left" value="{{ old('label_en',$menuItem?->label_en) }}"></div>
<div class="form-group col-lg-2 col-md-4"><label>قسم</label><select name="item_type" class="form-control"><option value="collection" @selected(($menuItem?->item_type??'collection')==='collection')>کلیکشن</option><option value="catalog" @selected($menuItem?->item_type==='catalog')>تمام مصنوعات</option><option value="tailoring" @selected($menuItem?->item_type==='tailoring')>ٹیلرنگ</option><option value="contact" @selected($menuItem?->item_type==='contact')>رابطہ</option><option value="external" @selected($menuItem?->item_type==='external')>بیرونی لنک</option></select></div>
<div class="form-group col-lg-2 col-md-4"><label>کلیکشن</label><select name="storefront_collection_id" class="form-control"><option value="">—</option>@foreach($collections as $option)<option value="{{ $option->id }}" @selected((int)$menuItem?->storefront_collection_id===$option->id)>{{ $option->name_ur ?: $option->name_en }}</option>@endforeach</select></div>
<div class="form-group col-lg-2 col-md-4"><label>والد مینو</label><select name="parent_id" class="form-control"><option value="">بنیادی مینو</option>@foreach($menuItems as $parent)<option value="{{ $parent->id }}" @selected((int)$menuItem?->parent_id===$parent->id) @disabled($menuItem?->id===$parent->id)>{{ $parent->label_ur ?: $parent->label_en }}</option>@endforeach</select></div>
<div class="form-group col-lg-2 col-md-4"><label>جگہ</label><select name="location" class="form-control"><option value="header" @selected(($menuItem?->location??'header')==='header')>ہیڈر</option><option value="footer" @selected($menuItem?->location==='footer')>فوٹر</option><option value="both" @selected($menuItem?->location==='both')>دونوں</option></select></div>
<div class="form-group col-md-6"><label>بیرونی URL</label><input name="url" dir="ltr" class="form-control text-left" value="{{ old('url',$menuItem?->url) }}" placeholder="https://..."></div><div class="form-group col-md-2"><label>ترتیب</label><input type="number" name="sort_order" min="0" max="9999" class="form-control" value="{{ old('sort_order',$menuItem?->sort_order??0) }}"></div><div class="form-group col-md-2"><label><input type="checkbox" name="is_visible" value="1" @checked(old('is_visible',$menuItem?->is_visible??true))> دکھائیں</label><br><label><input type="checkbox" name="open_in_new_tab" value="1" @checked(old('open_in_new_tab',$menuItem?->open_in_new_tab))> نئی ٹیب</label></div><div class="form-group col-md-2"><button class="btn btn-primary btn-block">محفوظ</button></div>
</div>
